begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Copyright (C) 2008 The Guava Authors  *  * Licensed under the Apache License, Version 2.0 (the "License");  * you may not use this file except in compliance with the License.  * You may obtain a copy of the License at  *  * http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
DECL|package|com.google.common.base
package|package
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|base
package|;
end_package

begin_class
DECL|class|StopwatchTest_gwt
specifier|public
class|class
name|StopwatchTest_gwt
extends|extends
name|com
operator|.
name|google
operator|.
name|gwt
operator|.
name|junit
operator|.
name|client
operator|.
name|GWTTestCase
block|{
DECL|method|getModuleName ()
annotation|@
name|Override
specifier|public
name|String
name|getModuleName
parameter_list|()
block|{
return|return
literal|"com.google.common.base.testModule"
return|;
block|}
DECL|method|testCreateStarted ()
specifier|public
name|void
name|testCreateStarted
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|base
operator|.
name|StopwatchTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|base
operator|.
name|StopwatchTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testCreateStarted
argument_list|()
expr_stmt|;
block|}
DECL|method|testCreateUnstarted ()
specifier|public
name|void
name|testCreateUnstarted
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|base
operator|.
name|StopwatchTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|base
operator|.
name|StopwatchTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testCreateUnstarted
argument_list|()
expr_stmt|;
block|}
DECL|method|testElapsed_micros ()
specifier|public
name|void
name|testElapsed_micros
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|base
operator|.
name|StopwatchTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|base
operator|.
name|StopwatchTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testElapsed_micros
argument_list|()
expr_stmt|;
block|}
DECL|method|testElapsed_millis ()
specifier|public
name|void
name|testElapsed_millis
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|base
operator|.
name|StopwatchTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|base
operator|.
name|StopwatchTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testElapsed_millis
argument_list|()
expr_stmt|;
block|}
DECL|method|testElapsed_multipleSegments ()
specifier|public
name|void
name|testElapsed_multipleSegments
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|base
operator|.
name|StopwatchTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|base
operator|.
name|StopwatchTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testElapsed_multipleSegments
argument_list|()
expr_stmt|;
block|}
DECL|method|testElapsed_notRunning ()
specifier|public
name|void
name|testElapsed_notRunning
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|base
operator|.
name|StopwatchTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|base
operator|.
name|StopwatchTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testElapsed_notRunning
argument_list|()
expr_stmt|;
block|}
DECL|method|testElapsed_whileRunning ()
specifier|public
name|void
name|testElapsed_whileRunning
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|base
operator|.
name|StopwatchTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|base
operator|.
name|StopwatchTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testElapsed_whileRunning
argument_list|()
expr_stmt|;
block|}
DECL|method|testInitialState ()
specifier|public
name|void
name|testInitialState
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|base
operator|.
name|StopwatchTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|base
operator|.
name|StopwatchTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testInitialState
argument_list|()
expr_stmt|;
block|}
DECL|method|testReset_new ()
specifier|public
name|void
name|testReset_new
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|base
operator|.
name|StopwatchTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|base
operator|.
name|StopwatchTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testReset_new
argument_list|()
expr_stmt|;
block|}
DECL|method|testReset_whileRunning ()
specifier|public
name|void
name|testReset_whileRunning
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|base
operator|.
name|StopwatchTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|base
operator|.
name|StopwatchTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testReset_whileRunning
argument_list|()
expr_stmt|;
block|}
DECL|method|testStart ()
specifier|public
name|void
name|testStart
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|base
operator|.
name|StopwatchTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|base
operator|.
name|StopwatchTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testStart
argument_list|()
expr_stmt|;
block|}
DECL|method|testStart_whileRunning ()
specifier|public
name|void
name|testStart_whileRunning
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|base
operator|.
name|StopwatchTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|base
operator|.
name|StopwatchTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testStart_whileRunning
argument_list|()
expr_stmt|;
block|}
DECL|method|testStop ()
specifier|public
name|void
name|testStop
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|base
operator|.
name|StopwatchTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|base
operator|.
name|StopwatchTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testStop
argument_list|()
expr_stmt|;
block|}
DECL|method|testStop_alreadyStopped ()
specifier|public
name|void
name|testStop_alreadyStopped
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|base
operator|.
name|StopwatchTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|base
operator|.
name|StopwatchTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testStop_alreadyStopped
argument_list|()
expr_stmt|;
block|}
DECL|method|testStop_new ()
specifier|public
name|void
name|testStop_new
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|base
operator|.
name|StopwatchTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|base
operator|.
name|StopwatchTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testStop_new
argument_list|()
expr_stmt|;
block|}
block|}
end_class

end_unit

