sudo: false

language: java

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

cache:
  directories:
  - $HOME/.m2

install: mvn install -U -DskipTests=true

script: mvn verify -U -Dmaven.javadoc.skip=true
