begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Copyright (C) 2015 The Guava Authors  *  * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except  * in compliance with the License. You may obtain a copy of the License at  *  * http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software distributed under the License  * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express  * or implied. See the License for the specific language governing permissions and limitations under  * the License.  */
end_comment

begin_package
DECL|package|com.google.common.collect
package|package
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
package|;
end_package

begin_import
import|import static
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|base
operator|.
name|Preconditions
operator|.
name|checkNotNull
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|annotations
operator|.
name|GwtCompatible
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Collections
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Queue
import|;
end_import

begin_comment
comment|/**  * An Iterator implementation which draws elements from a queue, removing them from the queue as it  * iterates.  */
end_comment

begin_class
annotation|@
name|GwtCompatible
DECL|class|ConsumingQueueIterator
class|class
name|ConsumingQueueIterator
parameter_list|<
name|T
parameter_list|>
extends|extends
name|AbstractIterator
argument_list|<
name|T
argument_list|>
block|{
DECL|field|queue
specifier|private
specifier|final
name|Queue
argument_list|<
name|T
argument_list|>
name|queue
decl_stmt|;
DECL|method|ConsumingQueueIterator (T... elements)
name|ConsumingQueueIterator
parameter_list|(
name|T
modifier|...
name|elements
parameter_list|)
block|{
comment|// Uses LinkedList because ArrayDeque isn't GWT-compatible for now =(
name|this
operator|.
name|queue
operator|=
name|Lists
operator|.
name|newLinkedList
argument_list|()
expr_stmt|;
name|Collections
operator|.
name|addAll
argument_list|(
name|queue
argument_list|,
name|elements
argument_list|)
expr_stmt|;
block|}
DECL|method|ConsumingQueueIterator (Queue<T> queue)
name|ConsumingQueueIterator
parameter_list|(
name|Queue
argument_list|<
name|T
argument_list|>
name|queue
parameter_list|)
block|{
name|this
operator|.
name|queue
operator|=
name|checkNotNull
argument_list|(
name|queue
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Override
DECL|method|computeNext ()
specifier|public
name|T
name|computeNext
parameter_list|()
block|{
return|return
name|queue
operator|.
name|isEmpty
argument_list|()
condition|?
name|endOfData
argument_list|()
else|:
name|queue
operator|.
name|remove
argument_list|()
return|;
block|}
block|}
end_class

end_unit

