begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Copyright (C) 2009 The Guava Authors  *  * Licensed under the Apache License, Version 2.0 (the "License");  * you may not use this file except in compliance with the License.  * You may obtain a copy of the License at  *  * http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
DECL|package|com.google.common.collect.testing
package|package
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|testing
package|;
end_package

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|annotations
operator|.
name|GwtCompatible
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|testing
operator|.
name|SampleElements
operator|.
name|Unhashables
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Collection
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|List
import|;
end_import

begin_comment
comment|/**  * Creates collections containing unhashable sample elements, to be tested.  *  * @author Regina O'Dell  */
end_comment

begin_class
annotation|@
name|GwtCompatible
DECL|class|TestUnhashableCollectionGenerator
specifier|public
specifier|abstract
class|class
name|TestUnhashableCollectionGenerator
parameter_list|<
name|T
extends|extends
name|Collection
parameter_list|<
name|UnhashableObject
parameter_list|>
parameter_list|>
implements|implements
name|TestCollectionGenerator
argument_list|<
name|UnhashableObject
argument_list|>
block|{
annotation|@
name|Override
DECL|method|samples ()
specifier|public
name|SampleElements
argument_list|<
name|UnhashableObject
argument_list|>
name|samples
parameter_list|()
block|{
return|return
operator|new
name|Unhashables
argument_list|()
return|;
block|}
annotation|@
name|Override
DECL|method|create (Object... elements)
specifier|public
name|T
name|create
parameter_list|(
name|Object
modifier|...
name|elements
parameter_list|)
block|{
name|UnhashableObject
index|[]
name|array
init|=
name|createArray
argument_list|(
name|elements
operator|.
name|length
argument_list|)
decl_stmt|;
name|int
name|i
init|=
literal|0
decl_stmt|;
for|for
control|(
name|Object
name|e
range|:
name|elements
control|)
block|{
name|array
index|[
name|i
operator|++
index|]
operator|=
operator|(
name|UnhashableObject
operator|)
name|e
expr_stmt|;
block|}
return|return
name|create
argument_list|(
name|array
argument_list|)
return|;
block|}
comment|/**    * Creates a new collection containing the given elements; implement this    * method instead of {@link #create(Object...)}.    */
DECL|method|create (UnhashableObject[] elements)
specifier|protected
specifier|abstract
name|T
name|create
parameter_list|(
name|UnhashableObject
index|[]
name|elements
parameter_list|)
function_decl|;
annotation|@
name|Override
DECL|method|createArray (int length)
specifier|public
name|UnhashableObject
index|[]
name|createArray
parameter_list|(
name|int
name|length
parameter_list|)
block|{
return|return
operator|new
name|UnhashableObject
index|[
name|length
index|]
return|;
block|}
annotation|@
name|Override
DECL|method|order (List<UnhashableObject> insertionOrder)
specifier|public
name|Iterable
argument_list|<
name|UnhashableObject
argument_list|>
name|order
parameter_list|(
name|List
argument_list|<
name|UnhashableObject
argument_list|>
name|insertionOrder
parameter_list|)
block|{
return|return
name|insertionOrder
return|;
block|}
block|}
end_class

end_unit

