begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Copyright (C) 2008 The Guava Authors  *  * Licensed under the Apache License, Version 2.0 (the "License");  * you may not use this file except in compliance with the License.  * You may obtain a copy of the License at  *  * http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
DECL|package|com.google.common.collect
package|package
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
package|;
end_package

begin_import
import|import static
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|Iterables
operator|.
name|concat
import|;
end_import

begin_import
import|import static
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|Lists
operator|.
name|newArrayList
import|;
end_import

begin_import
import|import static
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|Lists
operator|.
name|newLinkedList
import|;
end_import

begin_import
import|import static
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|truth
operator|.
name|Truth
operator|.
name|assertThat
import|;
end_import

begin_import
import|import static
name|java
operator|.
name|util
operator|.
name|Arrays
operator|.
name|asList
import|;
end_import

begin_import
import|import static
name|java
operator|.
name|util
operator|.
name|Collections
operator|.
name|nCopies
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|annotations
operator|.
name|GwtCompatible
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|annotations
operator|.
name|GwtIncompatible
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|base
operator|.
name|Function
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|base
operator|.
name|Predicate
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|testing
operator|.
name|CollectionTestSuiteBuilder
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|testing
operator|.
name|TestStringCollectionGenerator
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|testing
operator|.
name|features
operator|.
name|CollectionFeature
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|testing
operator|.
name|features
operator|.
name|CollectionSize
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|testing
operator|.
name|NullPointerTester
import|;
end_import

begin_import
import|import
name|junit
operator|.
name|framework
operator|.
name|Test
import|;
end_import

begin_import
import|import
name|junit
operator|.
name|framework
operator|.
name|TestCase
import|;
end_import

begin_import
import|import
name|junit
operator|.
name|framework
operator|.
name|TestSuite
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Collection
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Collections
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Iterator
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|List
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|NoSuchElementException
import|;
end_import

begin_comment
comment|/**  * Tests for {@link Collections2}.  *  * @author Chris Povirk  * @author Jared Levy  */
end_comment

begin_class
annotation|@
name|GwtCompatible
argument_list|(
name|emulated
operator|=
literal|true
argument_list|)
DECL|class|Collections2Test
specifier|public
class|class
name|Collections2Test
extends|extends
name|TestCase
block|{
annotation|@
name|GwtIncompatible
comment|// suite
DECL|method|suite ()
specifier|public
specifier|static
name|Test
name|suite
parameter_list|()
block|{
name|TestSuite
name|suite
init|=
operator|new
name|TestSuite
argument_list|(
name|Collections2Test
operator|.
name|class
operator|.
name|getSimpleName
argument_list|()
argument_list|)
decl_stmt|;
name|suite
operator|.
name|addTest
argument_list|(
name|testsForFilter
argument_list|()
argument_list|)
expr_stmt|;
name|suite
operator|.
name|addTest
argument_list|(
name|testsForFilterAll
argument_list|()
argument_list|)
expr_stmt|;
name|suite
operator|.
name|addTest
argument_list|(
name|testsForFilterLinkedList
argument_list|()
argument_list|)
expr_stmt|;
name|suite
operator|.
name|addTest
argument_list|(
name|testsForFilterNoNulls
argument_list|()
argument_list|)
expr_stmt|;
name|suite
operator|.
name|addTest
argument_list|(
name|testsForFilterFiltered
argument_list|()
argument_list|)
expr_stmt|;
name|suite
operator|.
name|addTest
argument_list|(
name|testsForTransform
argument_list|()
argument_list|)
expr_stmt|;
name|suite
operator|.
name|addTestSuite
argument_list|(
name|Collections2Test
operator|.
name|class
argument_list|)
expr_stmt|;
return|return
name|suite
return|;
block|}
DECL|field|NOT_YYY_ZZZ
specifier|static
specifier|final
name|Predicate
argument_list|<
name|String
argument_list|>
name|NOT_YYY_ZZZ
init|=
operator|new
name|Predicate
argument_list|<
name|String
argument_list|>
argument_list|()
block|{
annotation|@
name|Override
specifier|public
name|boolean
name|apply
parameter_list|(
name|String
name|input
parameter_list|)
block|{
return|return
operator|!
literal|"yyy"
operator|.
name|equals
argument_list|(
name|input
argument_list|)
operator|&&
operator|!
literal|"zzz"
operator|.
name|equals
argument_list|(
name|input
argument_list|)
return|;
block|}
block|}
decl_stmt|;
DECL|field|LENGTH_1
specifier|static
specifier|final
name|Predicate
argument_list|<
name|String
argument_list|>
name|LENGTH_1
init|=
operator|new
name|Predicate
argument_list|<
name|String
argument_list|>
argument_list|()
block|{
annotation|@
name|Override
specifier|public
name|boolean
name|apply
parameter_list|(
name|String
name|input
parameter_list|)
block|{
return|return
name|input
operator|.
name|length
argument_list|()
operator|==
literal|1
return|;
block|}
block|}
decl_stmt|;
DECL|field|STARTS_WITH_VOWEL
specifier|static
specifier|final
name|Predicate
argument_list|<
name|String
argument_list|>
name|STARTS_WITH_VOWEL
init|=
operator|new
name|Predicate
argument_list|<
name|String
argument_list|>
argument_list|()
block|{
annotation|@
name|Override
specifier|public
name|boolean
name|apply
parameter_list|(
name|String
name|input
parameter_list|)
block|{
return|return
name|asList
argument_list|(
literal|'a'
argument_list|,
literal|'e'
argument_list|,
literal|'i'
argument_list|,
literal|'o'
argument_list|,
literal|'u'
argument_list|)
operator|.
name|contains
argument_list|(
name|input
operator|.
name|charAt
argument_list|(
literal|0
argument_list|)
argument_list|)
return|;
block|}
block|}
decl_stmt|;
annotation|@
name|GwtIncompatible
comment|// suite
DECL|method|testsForFilter ()
specifier|private
specifier|static
name|Test
name|testsForFilter
parameter_list|()
block|{
return|return
name|CollectionTestSuiteBuilder
operator|.
name|using
argument_list|(
operator|new
name|TestStringCollectionGenerator
argument_list|()
block|{
annotation|@
name|Override
specifier|public
name|Collection
argument_list|<
name|String
argument_list|>
name|create
parameter_list|(
name|String
index|[]
name|elements
parameter_list|)
block|{
name|List
argument_list|<
name|String
argument_list|>
name|unfiltered
init|=
name|newArrayList
argument_list|()
decl_stmt|;
name|unfiltered
operator|.
name|add
argument_list|(
literal|"yyy"
argument_list|)
expr_stmt|;
name|Collections
operator|.
name|addAll
argument_list|(
name|unfiltered
argument_list|,
name|elements
argument_list|)
expr_stmt|;
name|unfiltered
operator|.
name|add
argument_list|(
literal|"zzz"
argument_list|)
expr_stmt|;
return|return
name|Collections2
operator|.
name|filter
argument_list|(
name|unfiltered
argument_list|,
name|NOT_YYY_ZZZ
argument_list|)
return|;
block|}
block|}
argument_list|)
operator|.
name|named
argument_list|(
literal|"Collections2.filter"
argument_list|)
operator|.
name|withFeatures
argument_list|(
name|CollectionFeature
operator|.
name|SUPPORTS_ADD
argument_list|,
name|CollectionFeature
operator|.
name|SUPPORTS_REMOVE
argument_list|,
name|CollectionFeature
operator|.
name|ALLOWS_NULL_VALUES
argument_list|,
name|CollectionFeature
operator|.
name|KNOWN_ORDER
argument_list|,
name|CollectionSize
operator|.
name|ANY
argument_list|)
operator|.
name|createTestSuite
argument_list|()
return|;
block|}
annotation|@
name|GwtIncompatible
comment|// suite
DECL|method|testsForFilterAll ()
specifier|private
specifier|static
name|Test
name|testsForFilterAll
parameter_list|()
block|{
return|return
name|CollectionTestSuiteBuilder
operator|.
name|using
argument_list|(
operator|new
name|TestStringCollectionGenerator
argument_list|()
block|{
annotation|@
name|Override
specifier|public
name|Collection
argument_list|<
name|String
argument_list|>
name|create
parameter_list|(
name|String
index|[]
name|elements
parameter_list|)
block|{
name|List
argument_list|<
name|String
argument_list|>
name|unfiltered
init|=
name|newArrayList
argument_list|()
decl_stmt|;
name|Collections
operator|.
name|addAll
argument_list|(
name|unfiltered
argument_list|,
name|elements
argument_list|)
expr_stmt|;
return|return
name|Collections2
operator|.
name|filter
argument_list|(
name|unfiltered
argument_list|,
name|NOT_YYY_ZZZ
argument_list|)
return|;
block|}
block|}
argument_list|)
operator|.
name|named
argument_list|(
literal|"Collections2.filter"
argument_list|)
operator|.
name|withFeatures
argument_list|(
name|CollectionFeature
operator|.
name|SUPPORTS_ADD
argument_list|,
name|CollectionFeature
operator|.
name|SUPPORTS_REMOVE
argument_list|,
name|CollectionFeature
operator|.
name|ALLOWS_NULL_VALUES
argument_list|,
name|CollectionFeature
operator|.
name|KNOWN_ORDER
argument_list|,
name|CollectionSize
operator|.
name|ANY
argument_list|)
operator|.
name|createTestSuite
argument_list|()
return|;
block|}
annotation|@
name|GwtIncompatible
comment|// suite
DECL|method|testsForFilterLinkedList ()
specifier|private
specifier|static
name|Test
name|testsForFilterLinkedList
parameter_list|()
block|{
return|return
name|CollectionTestSuiteBuilder
operator|.
name|using
argument_list|(
operator|new
name|TestStringCollectionGenerator
argument_list|()
block|{
annotation|@
name|Override
specifier|public
name|Collection
argument_list|<
name|String
argument_list|>
name|create
parameter_list|(
name|String
index|[]
name|elements
parameter_list|)
block|{
name|List
argument_list|<
name|String
argument_list|>
name|unfiltered
init|=
name|newLinkedList
argument_list|()
decl_stmt|;
name|unfiltered
operator|.
name|add
argument_list|(
literal|"yyy"
argument_list|)
expr_stmt|;
name|Collections
operator|.
name|addAll
argument_list|(
name|unfiltered
argument_list|,
name|elements
argument_list|)
expr_stmt|;
name|unfiltered
operator|.
name|add
argument_list|(
literal|"zzz"
argument_list|)
expr_stmt|;
return|return
name|Collections2
operator|.
name|filter
argument_list|(
name|unfiltered
argument_list|,
name|NOT_YYY_ZZZ
argument_list|)
return|;
block|}
block|}
argument_list|)
operator|.
name|named
argument_list|(
literal|"Collections2.filter"
argument_list|)
operator|.
name|withFeatures
argument_list|(
name|CollectionFeature
operator|.
name|SUPPORTS_ADD
argument_list|,
name|CollectionFeature
operator|.
name|SUPPORTS_REMOVE
argument_list|,
name|CollectionFeature
operator|.
name|ALLOWS_NULL_VALUES
argument_list|,
name|CollectionFeature
operator|.
name|KNOWN_ORDER
argument_list|,
name|CollectionSize
operator|.
name|ANY
argument_list|)
operator|.
name|createTestSuite
argument_list|()
return|;
block|}
annotation|@
name|GwtIncompatible
comment|// suite
DECL|method|testsForFilterNoNulls ()
specifier|private
specifier|static
name|Test
name|testsForFilterNoNulls
parameter_list|()
block|{
return|return
name|CollectionTestSuiteBuilder
operator|.
name|using
argument_list|(
operator|new
name|TestStringCollectionGenerator
argument_list|()
block|{
annotation|@
name|Override
specifier|public
name|Collection
argument_list|<
name|String
argument_list|>
name|create
parameter_list|(
name|String
index|[]
name|elements
parameter_list|)
block|{
name|List
argument_list|<
name|String
argument_list|>
name|unfiltered
init|=
name|newArrayList
argument_list|()
decl_stmt|;
name|unfiltered
operator|.
name|add
argument_list|(
literal|"yyy"
argument_list|)
expr_stmt|;
name|unfiltered
operator|.
name|addAll
argument_list|(
name|ImmutableList
operator|.
name|copyOf
argument_list|(
name|elements
argument_list|)
argument_list|)
expr_stmt|;
name|unfiltered
operator|.
name|add
argument_list|(
literal|"zzz"
argument_list|)
expr_stmt|;
return|return
name|Collections2
operator|.
name|filter
argument_list|(
name|unfiltered
argument_list|,
name|LENGTH_1
argument_list|)
return|;
block|}
block|}
argument_list|)
operator|.
name|named
argument_list|(
literal|"Collections2.filter, no nulls"
argument_list|)
operator|.
name|withFeatures
argument_list|(
name|CollectionFeature
operator|.
name|SUPPORTS_ADD
argument_list|,
name|CollectionFeature
operator|.
name|SUPPORTS_REMOVE
argument_list|,
name|CollectionFeature
operator|.
name|ALLOWS_NULL_QUERIES
argument_list|,
name|CollectionFeature
operator|.
name|KNOWN_ORDER
argument_list|,
name|CollectionSize
operator|.
name|ANY
argument_list|)
operator|.
name|createTestSuite
argument_list|()
return|;
block|}
annotation|@
name|GwtIncompatible
comment|// suite
DECL|method|testsForFilterFiltered ()
specifier|private
specifier|static
name|Test
name|testsForFilterFiltered
parameter_list|()
block|{
return|return
name|CollectionTestSuiteBuilder
operator|.
name|using
argument_list|(
operator|new
name|TestStringCollectionGenerator
argument_list|()
block|{
annotation|@
name|Override
specifier|public
name|Collection
argument_list|<
name|String
argument_list|>
name|create
parameter_list|(
name|String
index|[]
name|elements
parameter_list|)
block|{
name|List
argument_list|<
name|String
argument_list|>
name|unfiltered
init|=
name|newArrayList
argument_list|()
decl_stmt|;
name|unfiltered
operator|.
name|add
argument_list|(
literal|"yyy"
argument_list|)
expr_stmt|;
name|unfiltered
operator|.
name|addAll
argument_list|(
name|ImmutableList
operator|.
name|copyOf
argument_list|(
name|elements
argument_list|)
argument_list|)
expr_stmt|;
name|unfiltered
operator|.
name|add
argument_list|(
literal|"zzz"
argument_list|)
expr_stmt|;
name|unfiltered
operator|.
name|add
argument_list|(
literal|"abc"
argument_list|)
expr_stmt|;
return|return
name|Collections2
operator|.
name|filter
argument_list|(
name|Collections2
operator|.
name|filter
argument_list|(
name|unfiltered
argument_list|,
name|LENGTH_1
argument_list|)
argument_list|,
name|NOT_YYY_ZZZ
argument_list|)
return|;
block|}
block|}
argument_list|)
operator|.
name|named
argument_list|(
literal|"Collections2.filter, filtered input"
argument_list|)
operator|.
name|withFeatures
argument_list|(
name|CollectionFeature
operator|.
name|SUPPORTS_ADD
argument_list|,
name|CollectionFeature
operator|.
name|SUPPORTS_REMOVE
argument_list|,
name|CollectionFeature
operator|.
name|KNOWN_ORDER
argument_list|,
name|CollectionFeature
operator|.
name|ALLOWS_NULL_QUERIES
argument_list|,
name|CollectionSize
operator|.
name|ANY
argument_list|)
operator|.
name|createTestSuite
argument_list|()
return|;
block|}
DECL|field|REMOVE_FIRST_CHAR
specifier|private
specifier|static
specifier|final
name|Function
argument_list|<
name|String
argument_list|,
name|String
argument_list|>
name|REMOVE_FIRST_CHAR
init|=
operator|new
name|Function
argument_list|<
name|String
argument_list|,
name|String
argument_list|>
argument_list|()
block|{
annotation|@
name|Override
specifier|public
name|String
name|apply
parameter_list|(
name|String
name|from
parameter_list|)
block|{
return|return
operator|(
operator|(
name|from
operator|==
literal|null
operator|)
operator|||
literal|""
operator|.
name|equals
argument_list|(
name|from
argument_list|)
operator|)
condition|?
literal|null
else|:
name|from
operator|.
name|substring
argument_list|(
literal|1
argument_list|)
return|;
block|}
block|}
decl_stmt|;
annotation|@
name|GwtIncompatible
comment|// suite
DECL|method|testsForTransform ()
specifier|private
specifier|static
name|Test
name|testsForTransform
parameter_list|()
block|{
return|return
name|CollectionTestSuiteBuilder
operator|.
name|using
argument_list|(
operator|new
name|TestStringCollectionGenerator
argument_list|()
block|{
annotation|@
name|Override
specifier|public
name|Collection
argument_list|<
name|String
argument_list|>
name|create
parameter_list|(
name|String
index|[]
name|elements
parameter_list|)
block|{
name|List
argument_list|<
name|String
argument_list|>
name|list
init|=
name|newArrayList
argument_list|()
decl_stmt|;
for|for
control|(
name|String
name|element
range|:
name|elements
control|)
block|{
name|list
operator|.
name|add
argument_list|(
operator|(
name|element
operator|==
literal|null
operator|)
condition|?
literal|null
else|:
literal|"q"
operator|+
name|element
argument_list|)
expr_stmt|;
block|}
return|return
name|Collections2
operator|.
name|transform
argument_list|(
name|list
argument_list|,
name|REMOVE_FIRST_CHAR
argument_list|)
return|;
block|}
block|}
argument_list|)
operator|.
name|named
argument_list|(
literal|"Collections2.transform"
argument_list|)
operator|.
name|withFeatures
argument_list|(
name|CollectionFeature
operator|.
name|REMOVE_OPERATIONS
argument_list|,
name|CollectionFeature
operator|.
name|ALLOWS_NULL_VALUES
argument_list|,
name|CollectionFeature
operator|.
name|KNOWN_ORDER
argument_list|,
name|CollectionSize
operator|.
name|ANY
argument_list|)
operator|.
name|createTestSuite
argument_list|()
return|;
block|}
annotation|@
name|GwtIncompatible
comment|// NullPointerTester
DECL|method|testNullPointerExceptions ()
specifier|public
name|void
name|testNullPointerExceptions
parameter_list|()
block|{
name|NullPointerTester
name|tester
init|=
operator|new
name|NullPointerTester
argument_list|()
decl_stmt|;
name|tester
operator|.
name|testAllPublicStaticMethods
argument_list|(
name|Collections2
operator|.
name|class
argument_list|)
expr_stmt|;
block|}
DECL|method|testOrderedPermutationSetEmpty ()
specifier|public
name|void
name|testOrderedPermutationSetEmpty
parameter_list|()
block|{
name|List
argument_list|<
name|Integer
argument_list|>
name|list
init|=
name|newArrayList
argument_list|()
decl_stmt|;
name|Collection
argument_list|<
name|List
argument_list|<
name|Integer
argument_list|>
argument_list|>
name|permutationSet
init|=
name|Collections2
operator|.
name|orderedPermutations
argument_list|(
name|list
argument_list|)
decl_stmt|;
name|assertEquals
argument_list|(
literal|1
argument_list|,
name|permutationSet
operator|.
name|size
argument_list|()
argument_list|)
expr_stmt|;
name|assertThat
argument_list|(
name|permutationSet
argument_list|)
operator|.
name|contains
argument_list|(
name|list
argument_list|)
expr_stmt|;
name|Iterator
argument_list|<
name|List
argument_list|<
name|Integer
argument_list|>
argument_list|>
name|permutations
init|=
name|permutationSet
operator|.
name|iterator
argument_list|()
decl_stmt|;
name|assertNextPermutation
argument_list|(
name|Lists
operator|.
expr|<
name|Integer
operator|>
name|newArrayList
argument_list|()
argument_list|,
name|permutations
argument_list|)
expr_stmt|;
name|assertNoMorePermutations
argument_list|(
name|permutations
argument_list|)
expr_stmt|;
block|}
DECL|method|testOrderedPermutationSetOneElement ()
specifier|public
name|void
name|testOrderedPermutationSetOneElement
parameter_list|()
block|{
name|List
argument_list|<
name|Integer
argument_list|>
name|list
init|=
name|newArrayList
argument_list|(
literal|1
argument_list|)
decl_stmt|;
name|Iterator
argument_list|<
name|List
argument_list|<
name|Integer
argument_list|>
argument_list|>
name|permutations
init|=
name|Collections2
operator|.
name|orderedPermutations
argument_list|(
name|list
argument_list|)
operator|.
name|iterator
argument_list|()
decl_stmt|;
name|assertNextPermutation
argument_list|(
name|newArrayList
argument_list|(
literal|1
argument_list|)
argument_list|,
name|permutations
argument_list|)
expr_stmt|;
name|assertNoMorePermutations
argument_list|(
name|permutations
argument_list|)
expr_stmt|;
block|}
DECL|method|testOrderedPermutationSetThreeElements ()
specifier|public
name|void
name|testOrderedPermutationSetThreeElements
parameter_list|()
block|{
name|List
argument_list|<
name|String
argument_list|>
name|list
init|=
name|newArrayList
argument_list|(
literal|"b"
argument_list|,
literal|"a"
argument_list|,
literal|"c"
argument_list|)
decl_stmt|;
name|Iterator
argument_list|<
name|List
argument_list|<
name|String
argument_list|>
argument_list|>
name|permutations
init|=
name|Collections2
operator|.
name|orderedPermutations
argument_list|(
name|list
argument_list|)
operator|.
name|iterator
argument_list|()
decl_stmt|;
name|assertNextPermutation
argument_list|(
name|newArrayList
argument_list|(
literal|"a"
argument_list|,
literal|"b"
argument_list|,
literal|"c"
argument_list|)
argument_list|,
name|permutations
argument_list|)
expr_stmt|;
name|assertNextPermutation
argument_list|(
name|newArrayList
argument_list|(
literal|"a"
argument_list|,
literal|"c"
argument_list|,
literal|"b"
argument_list|)
argument_list|,
name|permutations
argument_list|)
expr_stmt|;
name|assertNextPermutation
argument_list|(
name|newArrayList
argument_list|(
literal|"b"
argument_list|,
literal|"a"
argument_list|,
literal|"c"
argument_list|)
argument_list|,
name|permutations
argument_list|)
expr_stmt|;
name|assertNextPermutation
argument_list|(
name|newArrayList
argument_list|(
literal|"b"
argument_list|,
literal|"c"
argument_list|,
literal|"a"
argument_list|)
argument_list|,
name|permutations
argument_list|)
expr_stmt|;
name|assertNextPermutation
argument_list|(
name|newArrayList
argument_list|(
literal|"c"
argument_list|,
literal|"a"
argument_list|,
literal|"b"
argument_list|)
argument_list|,
name|permutations
argument_list|)
expr_stmt|;
name|assertNextPermutation
argument_list|(
name|newArrayList
argument_list|(
literal|"c"
argument_list|,
literal|"b"
argument_list|,
literal|"a"
argument_list|)
argument_list|,
name|permutations
argument_list|)
expr_stmt|;
name|assertNoMorePermutations
argument_list|(
name|permutations
argument_list|)
expr_stmt|;
block|}
DECL|method|testOrderedPermutationSetRepeatedElements ()
specifier|public
name|void
name|testOrderedPermutationSetRepeatedElements
parameter_list|()
block|{
name|List
argument_list|<
name|Integer
argument_list|>
name|list
init|=
name|newArrayList
argument_list|(
literal|1
argument_list|,
literal|1
argument_list|,
literal|2
argument_list|,
literal|2
argument_list|)
decl_stmt|;
name|Iterator
argument_list|<
name|List
argument_list|<
name|Integer
argument_list|>
argument_list|>
name|permutations
init|=
name|Collections2
operator|.
name|orderedPermutations
argument_list|(
name|list
argument_list|,
name|Ordering
operator|.
name|natural
argument_list|()
argument_list|)
operator|.
name|iterator
argument_list|()
decl_stmt|;
name|assertNextPermutation
argument_list|(
name|newArrayList
argument_list|(
literal|1
argument_list|,
literal|1
argument_list|,
literal|2
argument_list|,
literal|2
argument_list|)
argument_list|,
name|permutations
argument_list|)
expr_stmt|;
name|assertNextPermutation
argument_list|(
name|newArrayList
argument_list|(
literal|1
argument_list|,
literal|2
argument_list|,
literal|1
argument_list|,
literal|2
argument_list|)
argument_list|,
name|permutations
argument_list|)
expr_stmt|;
name|assertNextPermutation
argument_list|(
name|newArrayList
argument_list|(
literal|1
argument_list|,
literal|2
argument_list|,
literal|2
argument_list|,
literal|1
argument_list|)
argument_list|,
name|permutations
argument_list|)
expr_stmt|;
name|assertNextPermutation
argument_list|(
name|newArrayList
argument_list|(
literal|2
argument_list|,
literal|1
argument_list|,
literal|1
argument_list|,
literal|2
argument_list|)
argument_list|,
name|permutations
argument_list|)
expr_stmt|;
name|assertNextPermutation
argument_list|(
name|newArrayList
argument_list|(
literal|2
argument_list|,
literal|1
argument_list|,
literal|2
argument_list|,
literal|1
argument_list|)
argument_list|,
name|permutations
argument_list|)
expr_stmt|;
name|assertNextPermutation
argument_list|(
name|newArrayList
argument_list|(
literal|2
argument_list|,
literal|2
argument_list|,
literal|1
argument_list|,
literal|1
argument_list|)
argument_list|,
name|permutations
argument_list|)
expr_stmt|;
name|assertNoMorePermutations
argument_list|(
name|permutations
argument_list|)
expr_stmt|;
block|}
DECL|method|testOrderedPermutationSetRepeatedElementsSize ()
specifier|public
name|void
name|testOrderedPermutationSetRepeatedElementsSize
parameter_list|()
block|{
name|List
argument_list|<
name|Integer
argument_list|>
name|list
init|=
name|newArrayList
argument_list|(
literal|1
argument_list|,
literal|1
argument_list|,
literal|1
argument_list|,
literal|1
argument_list|,
literal|2
argument_list|,
literal|2
argument_list|,
literal|3
argument_list|)
decl_stmt|;
name|Collection
argument_list|<
name|List
argument_list|<
name|Integer
argument_list|>
argument_list|>
name|permutations
init|=
name|Collections2
operator|.
name|orderedPermutations
argument_list|(
name|list
argument_list|,
name|Ordering
operator|.
name|natural
argument_list|()
argument_list|)
decl_stmt|;
name|assertPermutationsCount
argument_list|(
literal|105
argument_list|,
name|permutations
argument_list|)
expr_stmt|;
block|}
DECL|method|testOrderedPermutationSetSizeOverflow ()
specifier|public
name|void
name|testOrderedPermutationSetSizeOverflow
parameter_list|()
block|{
comment|// 12 elements won't overflow
name|assertEquals
argument_list|(
literal|479001600
comment|/*12!*/
argument_list|,
name|Collections2
operator|.
name|orderedPermutations
argument_list|(
name|newArrayList
argument_list|(
literal|1
argument_list|,
literal|2
argument_list|,
literal|3
argument_list|,
literal|4
argument_list|,
literal|5
argument_list|,
literal|6
argument_list|,
literal|7
argument_list|,
literal|8
argument_list|,
literal|9
argument_list|,
literal|10
argument_list|,
literal|11
argument_list|,
literal|12
argument_list|)
argument_list|)
operator|.
name|size
argument_list|()
argument_list|)
expr_stmt|;
comment|// 13 elements overflow an int
name|assertEquals
argument_list|(
name|Integer
operator|.
name|MAX_VALUE
argument_list|,
name|Collections2
operator|.
name|orderedPermutations
argument_list|(
name|newArrayList
argument_list|(
literal|1
argument_list|,
literal|2
argument_list|,
literal|3
argument_list|,
literal|4
argument_list|,
literal|5
argument_list|,
literal|6
argument_list|,
literal|7
argument_list|,
literal|8
argument_list|,
literal|9
argument_list|,
literal|10
argument_list|,
literal|11
argument_list|,
literal|12
argument_list|,
literal|13
argument_list|)
argument_list|)
operator|.
name|size
argument_list|()
argument_list|)
expr_stmt|;
comment|// 21 elements overflow a long
name|assertEquals
argument_list|(
name|Integer
operator|.
name|MAX_VALUE
argument_list|,
name|Collections2
operator|.
name|orderedPermutations
argument_list|(
name|newArrayList
argument_list|(
literal|1
argument_list|,
literal|2
argument_list|,
literal|3
argument_list|,
literal|4
argument_list|,
literal|5
argument_list|,
literal|6
argument_list|,
literal|7
argument_list|,
literal|8
argument_list|,
literal|9
argument_list|,
literal|10
argument_list|,
literal|11
argument_list|,
literal|12
argument_list|,
literal|13
argument_list|,
literal|14
argument_list|,
literal|15
argument_list|,
literal|16
argument_list|,
literal|17
argument_list|,
literal|18
argument_list|,
literal|19
argument_list|,
literal|20
argument_list|,
literal|21
argument_list|)
argument_list|)
operator|.
name|size
argument_list|()
argument_list|)
expr_stmt|;
comment|// Almost force an overflow in the binomial coefficient calculation
name|assertEquals
argument_list|(
literal|1391975640
comment|/*C(34,14)*/
argument_list|,
name|Collections2
operator|.
name|orderedPermutations
argument_list|(
name|concat
argument_list|(
name|nCopies
argument_list|(
literal|20
argument_list|,
literal|1
argument_list|)
argument_list|,
name|nCopies
argument_list|(
literal|14
argument_list|,
literal|2
argument_list|)
argument_list|)
argument_list|)
operator|.
name|size
argument_list|()
argument_list|)
expr_stmt|;
comment|// Do force an overflow in the binomial coefficient calculation
name|assertEquals
argument_list|(
name|Integer
operator|.
name|MAX_VALUE
argument_list|,
name|Collections2
operator|.
name|orderedPermutations
argument_list|(
name|concat
argument_list|(
name|nCopies
argument_list|(
literal|21
argument_list|,
literal|1
argument_list|)
argument_list|,
name|nCopies
argument_list|(
literal|14
argument_list|,
literal|2
argument_list|)
argument_list|)
argument_list|)
operator|.
name|size
argument_list|()
argument_list|)
expr_stmt|;
block|}
DECL|method|testOrderedPermutationSetContains ()
specifier|public
name|void
name|testOrderedPermutationSetContains
parameter_list|()
block|{
name|List
argument_list|<
name|Integer
argument_list|>
name|list
init|=
name|newArrayList
argument_list|(
literal|3
argument_list|,
literal|2
argument_list|,
literal|1
argument_list|)
decl_stmt|;
name|Collection
argument_list|<
name|List
argument_list|<
name|Integer
argument_list|>
argument_list|>
name|permutationSet
init|=
name|Collections2
operator|.
name|orderedPermutations
argument_list|(
name|list
argument_list|)
decl_stmt|;
name|assertTrue
argument_list|(
name|permutationSet
operator|.
name|contains
argument_list|(
name|newArrayList
argument_list|(
literal|1
argument_list|,
literal|2
argument_list|,
literal|3
argument_list|)
argument_list|)
argument_list|)
expr_stmt|;
name|assertTrue
argument_list|(
name|permutationSet
operator|.
name|contains
argument_list|(
name|newArrayList
argument_list|(
literal|2
argument_list|,
literal|3
argument_list|,
literal|1
argument_list|)
argument_list|)
argument_list|)
expr_stmt|;
name|assertFalse
argument_list|(
name|permutationSet
operator|.
name|contains
argument_list|(
name|newArrayList
argument_list|(
literal|1
argument_list|,
literal|2
argument_list|)
argument_list|)
argument_list|)
expr_stmt|;
name|assertFalse
argument_list|(
name|permutationSet
operator|.
name|contains
argument_list|(
name|newArrayList
argument_list|(
literal|1
argument_list|,
literal|1
argument_list|,
literal|2
argument_list|,
literal|3
argument_list|)
argument_list|)
argument_list|)
expr_stmt|;
name|assertFalse
argument_list|(
name|permutationSet
operator|.
name|contains
argument_list|(
name|newArrayList
argument_list|(
literal|1
argument_list|,
literal|2
argument_list|,
literal|3
argument_list|,
literal|4
argument_list|)
argument_list|)
argument_list|)
expr_stmt|;
name|assertFalse
argument_list|(
name|permutationSet
operator|.
name|contains
argument_list|(
literal|null
argument_list|)
argument_list|)
expr_stmt|;
block|}
DECL|method|testPermutationSetEmpty ()
specifier|public
name|void
name|testPermutationSetEmpty
parameter_list|()
block|{
name|Collection
argument_list|<
name|List
argument_list|<
name|Integer
argument_list|>
argument_list|>
name|permutationSet
init|=
name|Collections2
operator|.
name|permutations
argument_list|(
name|Collections
operator|.
expr|<
name|Integer
operator|>
name|emptyList
argument_list|()
argument_list|)
decl_stmt|;
name|assertEquals
argument_list|(
literal|1
argument_list|,
name|permutationSet
operator|.
name|size
argument_list|()
argument_list|)
expr_stmt|;
name|assertTrue
argument_list|(
name|permutationSet
operator|.
name|contains
argument_list|(
name|Collections
operator|.
expr|<
name|Integer
operator|>
name|emptyList
argument_list|()
argument_list|)
argument_list|)
expr_stmt|;
name|Iterator
argument_list|<
name|List
argument_list|<
name|Integer
argument_list|>
argument_list|>
name|permutations
init|=
name|permutationSet
operator|.
name|iterator
argument_list|()
decl_stmt|;
name|assertNextPermutation
argument_list|(
name|Collections
operator|.
expr|<
name|Integer
operator|>
name|emptyList
argument_list|()
argument_list|,
name|permutations
argument_list|)
expr_stmt|;
name|assertNoMorePermutations
argument_list|(
name|permutations
argument_list|)
expr_stmt|;
block|}
DECL|method|testPermutationSetOneElement ()
specifier|public
name|void
name|testPermutationSetOneElement
parameter_list|()
block|{
name|Iterator
argument_list|<
name|List
argument_list|<
name|Integer
argument_list|>
argument_list|>
name|permutations
init|=
name|Collections2
operator|.
name|permutations
argument_list|(
name|Collections
operator|.
expr|<
name|Integer
operator|>
name|singletonList
argument_list|(
literal|1
argument_list|)
argument_list|)
operator|.
name|iterator
argument_list|()
decl_stmt|;
name|assertNextPermutation
argument_list|(
name|newArrayList
argument_list|(
literal|1
argument_list|)
argument_list|,
name|permutations
argument_list|)
expr_stmt|;
name|assertNoMorePermutations
argument_list|(
name|permutations
argument_list|)
expr_stmt|;
block|}
DECL|method|testPermutationSetTwoElements ()
specifier|public
name|void
name|testPermutationSetTwoElements
parameter_list|()
block|{
name|Iterator
argument_list|<
name|List
argument_list|<
name|Integer
argument_list|>
argument_list|>
name|permutations
init|=
name|Collections2
operator|.
name|permutations
argument_list|(
name|newArrayList
argument_list|(
literal|1
argument_list|,
literal|2
argument_list|)
argument_list|)
operator|.
name|iterator
argument_list|()
decl_stmt|;
name|assertNextPermutation
argument_list|(
name|newArrayList
argument_list|(
literal|1
argument_list|,
literal|2
argument_list|)
argument_list|,
name|permutations
argument_list|)
expr_stmt|;
name|assertNextPermutation
argument_list|(
name|newArrayList
argument_list|(
literal|2
argument_list|,
literal|1
argument_list|)
argument_list|,
name|permutations
argument_list|)
expr_stmt|;
name|assertNoMorePermutations
argument_list|(
name|permutations
argument_list|)
expr_stmt|;
block|}
DECL|method|testPermutationSetThreeElements ()
specifier|public
name|void
name|testPermutationSetThreeElements
parameter_list|()
block|{
name|Iterator
argument_list|<
name|List
argument_list|<
name|Integer
argument_list|>
argument_list|>
name|permutations
init|=
name|Collections2
operator|.
name|permutations
argument_list|(
name|newArrayList
argument_list|(
literal|1
argument_list|,
literal|2
argument_list|,
literal|3
argument_list|)
argument_list|)
operator|.
name|iterator
argument_list|()
decl_stmt|;
name|assertNextPermutation
argument_list|(
name|newArrayList
argument_list|(
literal|1
argument_list|,
literal|2
argument_list|,
literal|3
argument_list|)
argument_list|,
name|permutations
argument_list|)
expr_stmt|;
name|assertNextPermutation
argument_list|(
name|newArrayList
argument_list|(
literal|1
argument_list|,
literal|3
argument_list|,
literal|2
argument_list|)
argument_list|,
name|permutations
argument_list|)
expr_stmt|;
name|assertNextPermutation
argument_list|(
name|newArrayList
argument_list|(
literal|3
argument_list|,
literal|1
argument_list|,
literal|2
argument_list|)
argument_list|,
name|permutations
argument_list|)
expr_stmt|;
name|assertNextPermutation
argument_list|(
name|newArrayList
argument_list|(
literal|3
argument_list|,
literal|2
argument_list|,
literal|1
argument_list|)
argument_list|,
name|permutations
argument_list|)
expr_stmt|;
name|assertNextPermutation
argument_list|(
name|newArrayList
argument_list|(
literal|2
argument_list|,
literal|3
argument_list|,
literal|1
argument_list|)
argument_list|,
name|permutations
argument_list|)
expr_stmt|;
name|assertNextPermutation
argument_list|(
name|newArrayList
argument_list|(
literal|2
argument_list|,
literal|1
argument_list|,
literal|3
argument_list|)
argument_list|,
name|permutations
argument_list|)
expr_stmt|;
name|assertNoMorePermutations
argument_list|(
name|permutations
argument_list|)
expr_stmt|;
block|}
DECL|method|testPermutationSetThreeElementsOutOfOrder ()
specifier|public
name|void
name|testPermutationSetThreeElementsOutOfOrder
parameter_list|()
block|{
name|Iterator
argument_list|<
name|List
argument_list|<
name|Integer
argument_list|>
argument_list|>
name|permutations
init|=
name|Collections2
operator|.
name|permutations
argument_list|(
name|newArrayList
argument_list|(
literal|3
argument_list|,
literal|2
argument_list|,
literal|1
argument_list|)
argument_list|)
operator|.
name|iterator
argument_list|()
decl_stmt|;
name|assertNextPermutation
argument_list|(
name|newArrayList
argument_list|(
literal|3
argument_list|,
literal|2
argument_list|,
literal|1
argument_list|)
argument_list|,
name|permutations
argument_list|)
expr_stmt|;
name|assertNextPermutation
argument_list|(
name|newArrayList
argument_list|(
literal|3
argument_list|,
literal|1
argument_list|,
literal|2
argument_list|)
argument_list|,
name|permutations
argument_list|)
expr_stmt|;
name|assertNextPermutation
argument_list|(
name|newArrayList
argument_list|(
literal|1
argument_list|,
literal|3
argument_list|,
literal|2
argument_list|)
argument_list|,
name|permutations
argument_list|)
expr_stmt|;
name|assertNextPermutation
argument_list|(
name|newArrayList
argument_list|(
literal|1
argument_list|,
literal|2
argument_list|,
literal|3
argument_list|)
argument_list|,
name|permutations
argument_list|)
expr_stmt|;
name|assertNextPermutation
argument_list|(
name|newArrayList
argument_list|(
literal|2
argument_list|,
literal|1
argument_list|,
literal|3
argument_list|)
argument_list|,
name|permutations
argument_list|)
expr_stmt|;
name|assertNextPermutation
argument_list|(
name|newArrayList
argument_list|(
literal|2
argument_list|,
literal|3
argument_list|,
literal|1
argument_list|)
argument_list|,
name|permutations
argument_list|)
expr_stmt|;
name|assertNoMorePermutations
argument_list|(
name|permutations
argument_list|)
expr_stmt|;
block|}
DECL|method|testPermutationSetThreeRepeatedElements ()
specifier|public
name|void
name|testPermutationSetThreeRepeatedElements
parameter_list|()
block|{
name|Iterator
argument_list|<
name|List
argument_list|<
name|Integer
argument_list|>
argument_list|>
name|permutations
init|=
name|Collections2
operator|.
name|permutations
argument_list|(
name|newArrayList
argument_list|(
literal|1
argument_list|,
literal|1
argument_list|,
literal|2
argument_list|)
argument_list|)
operator|.
name|iterator
argument_list|()
decl_stmt|;
name|assertNextPermutation
argument_list|(
name|newArrayList
argument_list|(
literal|1
argument_list|,
literal|1
argument_list|,
literal|2
argument_list|)
argument_list|,
name|permutations
argument_list|)
expr_stmt|;
name|assertNextPermutation
argument_list|(
name|newArrayList
argument_list|(
literal|1
argument_list|,
literal|2
argument_list|,
literal|1
argument_list|)
argument_list|,
name|permutations
argument_list|)
expr_stmt|;
name|assertNextPermutation
argument_list|(
name|newArrayList
argument_list|(
literal|2
argument_list|,
literal|1
argument_list|,
literal|1
argument_list|)
argument_list|,
name|permutations
argument_list|)
expr_stmt|;
name|assertNextPermutation
argument_list|(
name|newArrayList
argument_list|(
literal|2
argument_list|,
literal|1
argument_list|,
literal|1
argument_list|)
argument_list|,
name|permutations
argument_list|)
expr_stmt|;
name|assertNextPermutation
argument_list|(
name|newArrayList
argument_list|(
literal|1
argument_list|,
literal|2
argument_list|,
literal|1
argument_list|)
argument_list|,
name|permutations
argument_list|)
expr_stmt|;
name|assertNextPermutation
argument_list|(
name|newArrayList
argument_list|(
literal|1
argument_list|,
literal|1
argument_list|,
literal|2
argument_list|)
argument_list|,
name|permutations
argument_list|)
expr_stmt|;
name|assertNoMorePermutations
argument_list|(
name|permutations
argument_list|)
expr_stmt|;
block|}
DECL|method|testPermutationSetFourElements ()
specifier|public
name|void
name|testPermutationSetFourElements
parameter_list|()
block|{
name|Iterator
argument_list|<
name|List
argument_list|<
name|Integer
argument_list|>
argument_list|>
name|permutations
init|=
name|Collections2
operator|.
name|permutations
argument_list|(
name|newArrayList
argument_list|(
literal|1
argument_list|,
literal|2
argument_list|,
literal|3
argument_list|,
literal|4
argument_list|)
argument_list|)
operator|.
name|iterator
argument_list|()
decl_stmt|;
name|assertNextPermutation
argument_list|(
name|newArrayList
argument_list|(
literal|1
argument_list|,
literal|2
argument_list|,
literal|3
argument_list|,
literal|4
argument_list|)
argument_list|,
name|permutations
argument_list|)
expr_stmt|;
name|assertNextPermutation
argument_list|(
name|newArrayList
argument_list|(
literal|1
argument_list|,
literal|2
argument_list|,
literal|4
argument_list|,
literal|3
argument_list|)
argument_list|,
name|permutations
argument_list|)
expr_stmt|;
name|assertNextPermutation
argument_list|(
name|newArrayList
argument_list|(
literal|1
argument_list|,
literal|4
argument_list|,
literal|2
argument_list|,
literal|3
argument_list|)
argument_list|,
name|permutations
argument_list|)
expr_stmt|;
name|assertNextPermutation
argument_list|(
name|newArrayList
argument_list|(
literal|4
argument_list|,
literal|1
argument_list|,
literal|2
argument_list|,
literal|3
argument_list|)
argument_list|,
name|permutations
argument_list|)
expr_stmt|;
name|assertNextPermutation
argument_list|(
name|newArrayList
argument_list|(
literal|4
argument_list|,
literal|1
argument_list|,
literal|3
argument_list|,
literal|2
argument_list|)
argument_list|,
name|permutations
argument_list|)
expr_stmt|;
name|assertNextPermutation
argument_list|(
name|newArrayList
argument_list|(
literal|1
argument_list|,
literal|4
argument_list|,
literal|3
argument_list|,
literal|2
argument_list|)
argument_list|,
name|permutations
argument_list|)
expr_stmt|;
name|assertNextPermutation
argument_list|(
name|newArrayList
argument_list|(
literal|1
argument_list|,
literal|3
argument_list|,
literal|4
argument_list|,
literal|2
argument_list|)
argument_list|,
name|permutations
argument_list|)
expr_stmt|;
name|assertNextPermutation
argument_list|(
name|newArrayList
argument_list|(
literal|1
argument_list|,
literal|3
argument_list|,
literal|2
argument_list|,
literal|4
argument_list|)
argument_list|,
name|permutations
argument_list|)
expr_stmt|;
name|assertNextPermutation
argument_list|(
name|newArrayList
argument_list|(
literal|3
argument_list|,
literal|1
argument_list|,
literal|2
argument_list|,
literal|4
argument_list|)
argument_list|,
name|permutations
argument_list|)
expr_stmt|;
name|assertNextPermutation
argument_list|(
name|newArrayList
argument_list|(
literal|3
argument_list|,
literal|1
argument_list|,
literal|4
argument_list|,
literal|2
argument_list|)
argument_list|,
name|permutations
argument_list|)
expr_stmt|;
name|assertNextPermutation
argument_list|(
name|newArrayList
argument_list|(
literal|3
argument_list|,
literal|4
argument_list|,
literal|1
argument_list|,
literal|2
argument_list|)
argument_list|,
name|permutations
argument_list|)
expr_stmt|;
name|assertNextPermutation
argument_list|(
name|newArrayList
argument_list|(
literal|4
argument_list|,
literal|3
argument_list|,
literal|1
argument_list|,
literal|2
argument_list|)
argument_list|,
name|permutations
argument_list|)
expr_stmt|;
name|assertNextPermutation
argument_list|(
name|newArrayList
argument_list|(
literal|4
argument_list|,
literal|3
argument_list|,
literal|2
argument_list|,
literal|1
argument_list|)
argument_list|,
name|permutations
argument_list|)
expr_stmt|;
name|assertNextPermutation
argument_list|(
name|newArrayList
argument_list|(
literal|3
argument_list|,
literal|4
argument_list|,
literal|2
argument_list|,
literal|1
argument_list|)
argument_list|,
name|permutations
argument_list|)
expr_stmt|;
name|assertNextPermutation
argument_list|(
name|newArrayList
argument_list|(
literal|3
argument_list|,
literal|2
argument_list|,
literal|4
argument_list|,
literal|1
argument_list|)
argument_list|,
name|permutations
argument_list|)
expr_stmt|;
name|assertNextPermutation
argument_list|(
name|newArrayList
argument_list|(
literal|3
argument_list|,
literal|2
argument_list|,
literal|1
argument_list|,
literal|4
argument_list|)
argument_list|,
name|permutations
argument_list|)
expr_stmt|;
name|assertNextPermutation
argument_list|(
name|newArrayList
argument_list|(
literal|2
argument_list|,
literal|3
argument_list|,
literal|1
argument_list|,
literal|4
argument_list|)
argument_list|,
name|permutations
argument_list|)
expr_stmt|;
name|assertNextPermutation
argument_list|(
name|newArrayList
argument_list|(
literal|2
argument_list|,
literal|3
argument_list|,
literal|4
argument_list|,
literal|1
argument_list|)
argument_list|,
name|permutations
argument_list|)
expr_stmt|;
name|assertNextPermutation
argument_list|(
name|newArrayList
argument_list|(
literal|2
argument_list|,
literal|4
argument_list|,
literal|3
argument_list|,
literal|1
argument_list|)
argument_list|,
name|permutations
argument_list|)
expr_stmt|;
name|assertNextPermutation
argument_list|(
name|newArrayList
argument_list|(
literal|4
argument_list|,
literal|2
argument_list|,
literal|3
argument_list|,
literal|1
argument_list|)
argument_list|,
name|permutations
argument_list|)
expr_stmt|;
name|assertNextPermutation
argument_list|(
name|newArrayList
argument_list|(
literal|4
argument_list|,
literal|2
argument_list|,
literal|1
argument_list|,
literal|3
argument_list|)
argument_list|,
name|permutations
argument_list|)
expr_stmt|;
name|assertNextPermutation
argument_list|(
name|newArrayList
argument_list|(
literal|2
argument_list|,
literal|4
argument_list|,
literal|1
argument_list|,
literal|3
argument_list|)
argument_list|,
name|permutations
argument_list|)
expr_stmt|;
name|assertNextPermutation
argument_list|(
name|newArrayList
argument_list|(
literal|2
argument_list|,
literal|1
argument_list|,
literal|4
argument_list|,
literal|3
argument_list|)
argument_list|,
name|permutations
argument_list|)
expr_stmt|;
name|assertNextPermutation
argument_list|(
name|newArrayList
argument_list|(
literal|2
argument_list|,
literal|1
argument_list|,
literal|3
argument_list|,
literal|4
argument_list|)
argument_list|,
name|permutations
argument_list|)
expr_stmt|;
name|assertNoMorePermutations
argument_list|(
name|permutations
argument_list|)
expr_stmt|;
block|}
DECL|method|testPermutationSetSize ()
specifier|public
name|void
name|testPermutationSetSize
parameter_list|()
block|{
name|assertPermutationsCount
argument_list|(
literal|1
argument_list|,
name|Collections2
operator|.
name|permutations
argument_list|(
name|Collections
operator|.
expr|<
name|Integer
operator|>
name|emptyList
argument_list|()
argument_list|)
argument_list|)
expr_stmt|;
name|assertPermutationsCount
argument_list|(
literal|1
argument_list|,
name|Collections2
operator|.
name|permutations
argument_list|(
name|newArrayList
argument_list|(
literal|1
argument_list|)
argument_list|)
argument_list|)
expr_stmt|;
name|assertPermutationsCount
argument_list|(
literal|2
argument_list|,
name|Collections2
operator|.
name|permutations
argument_list|(
name|newArrayList
argument_list|(
literal|1
argument_list|,
literal|2
argument_list|)
argument_list|)
argument_list|)
expr_stmt|;
name|assertPermutationsCount
argument_list|(
literal|6
argument_list|,
name|Collections2
operator|.
name|permutations
argument_list|(
name|newArrayList
argument_list|(
literal|1
argument_list|,
literal|2
argument_list|,
literal|3
argument_list|)
argument_list|)
argument_list|)
expr_stmt|;
name|assertPermutationsCount
argument_list|(
literal|5040
argument_list|,
name|Collections2
operator|.
name|permutations
argument_list|(
name|newArrayList
argument_list|(
literal|1
argument_list|,
literal|2
argument_list|,
literal|3
argument_list|,
literal|4
argument_list|,
literal|5
argument_list|,
literal|6
argument_list|,
literal|7
argument_list|)
argument_list|)
argument_list|)
expr_stmt|;
name|assertPermutationsCount
argument_list|(
literal|40320
argument_list|,
name|Collections2
operator|.
name|permutations
argument_list|(
name|newArrayList
argument_list|(
literal|1
argument_list|,
literal|2
argument_list|,
literal|3
argument_list|,
literal|4
argument_list|,
literal|5
argument_list|,
literal|6
argument_list|,
literal|7
argument_list|,
literal|8
argument_list|)
argument_list|)
argument_list|)
expr_stmt|;
block|}
DECL|method|testPermutationSetSizeOverflow ()
specifier|public
name|void
name|testPermutationSetSizeOverflow
parameter_list|()
block|{
comment|// 13 elements overflow an int
name|assertEquals
argument_list|(
name|Integer
operator|.
name|MAX_VALUE
argument_list|,
name|Collections2
operator|.
name|permutations
argument_list|(
name|newArrayList
argument_list|(
literal|1
argument_list|,
literal|2
argument_list|,
literal|3
argument_list|,
literal|4
argument_list|,
literal|5
argument_list|,
literal|6
argument_list|,
literal|7
argument_list|,
literal|8
argument_list|,
literal|9
argument_list|,
literal|10
argument_list|,
literal|11
argument_list|,
literal|12
argument_list|,
literal|13
argument_list|)
argument_list|)
operator|.
name|size
argument_list|()
argument_list|)
expr_stmt|;
comment|// 21 elements overflow a long
name|assertEquals
argument_list|(
name|Integer
operator|.
name|MAX_VALUE
argument_list|,
name|Collections2
operator|.
name|orderedPermutations
argument_list|(
name|newArrayList
argument_list|(
literal|1
argument_list|,
literal|2
argument_list|,
literal|3
argument_list|,
literal|4
argument_list|,
literal|5
argument_list|,
literal|6
argument_list|,
literal|7
argument_list|,
literal|8
argument_list|,
literal|9
argument_list|,
literal|10
argument_list|,
literal|11
argument_list|,
literal|12
argument_list|,
literal|13
argument_list|,
literal|14
argument_list|,
literal|15
argument_list|,
literal|16
argument_list|,
literal|17
argument_list|,
literal|18
argument_list|,
literal|19
argument_list|,
literal|20
argument_list|)
argument_list|)
operator|.
name|size
argument_list|()
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
name|Integer
operator|.
name|MAX_VALUE
argument_list|,
name|Collections2
operator|.
name|orderedPermutations
argument_list|(
name|newArrayList
argument_list|(
literal|1
argument_list|,
literal|2
argument_list|,
literal|3
argument_list|,
literal|4
argument_list|,
literal|5
argument_list|,
literal|6
argument_list|,
literal|7
argument_list|,
literal|8
argument_list|,
literal|9
argument_list|,
literal|10
argument_list|,
literal|11
argument_list|,
literal|12
argument_list|,
literal|13
argument_list|,
literal|14
argument_list|,
literal|15
argument_list|,
literal|16
argument_list|,
literal|17
argument_list|,
literal|18
argument_list|,
literal|19
argument_list|,
literal|20
argument_list|,
literal|21
argument_list|)
argument_list|)
operator|.
name|size
argument_list|()
argument_list|)
expr_stmt|;
block|}
DECL|method|testPermutationSetContains ()
specifier|public
name|void
name|testPermutationSetContains
parameter_list|()
block|{
name|List
argument_list|<
name|Integer
argument_list|>
name|list
init|=
name|newArrayList
argument_list|(
literal|3
argument_list|,
literal|2
argument_list|,
literal|1
argument_list|)
decl_stmt|;
name|Collection
argument_list|<
name|List
argument_list|<
name|Integer
argument_list|>
argument_list|>
name|permutationSet
init|=
name|Collections2
operator|.
name|permutations
argument_list|(
name|list
argument_list|)
decl_stmt|;
name|assertTrue
argument_list|(
name|permutationSet
operator|.
name|contains
argument_list|(
name|newArrayList
argument_list|(
literal|1
argument_list|,
literal|2
argument_list|,
literal|3
argument_list|)
argument_list|)
argument_list|)
expr_stmt|;
name|assertTrue
argument_list|(
name|permutationSet
operator|.
name|contains
argument_list|(
name|newArrayList
argument_list|(
literal|2
argument_list|,
literal|3
argument_list|,
literal|1
argument_list|)
argument_list|)
argument_list|)
expr_stmt|;
name|assertFalse
argument_list|(
name|permutationSet
operator|.
name|contains
argument_list|(
name|newArrayList
argument_list|(
literal|1
argument_list|,
literal|2
argument_list|)
argument_list|)
argument_list|)
expr_stmt|;
name|assertFalse
argument_list|(
name|permutationSet
operator|.
name|contains
argument_list|(
name|newArrayList
argument_list|(
literal|1
argument_list|,
literal|1
argument_list|,
literal|2
argument_list|,
literal|3
argument_list|)
argument_list|)
argument_list|)
expr_stmt|;
name|assertFalse
argument_list|(
name|permutationSet
operator|.
name|contains
argument_list|(
name|newArrayList
argument_list|(
literal|1
argument_list|,
literal|2
argument_list|,
literal|3
argument_list|,
literal|4
argument_list|)
argument_list|)
argument_list|)
expr_stmt|;
name|assertFalse
argument_list|(
name|permutationSet
operator|.
name|contains
argument_list|(
literal|null
argument_list|)
argument_list|)
expr_stmt|;
block|}
DECL|method|assertNextPermutation (List<T> expectedPermutation, Iterator<List<T>> permutations)
specifier|private
parameter_list|<
name|T
parameter_list|>
name|void
name|assertNextPermutation
parameter_list|(
name|List
argument_list|<
name|T
argument_list|>
name|expectedPermutation
parameter_list|,
name|Iterator
argument_list|<
name|List
argument_list|<
name|T
argument_list|>
argument_list|>
name|permutations
parameter_list|)
block|{
name|assertTrue
argument_list|(
literal|"Expected another permutation, but there was none."
argument_list|,
name|permutations
operator|.
name|hasNext
argument_list|()
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
name|expectedPermutation
argument_list|,
name|permutations
operator|.
name|next
argument_list|()
argument_list|)
expr_stmt|;
block|}
DECL|method|assertNoMorePermutations ( Iterator<List<T>> permutations)
specifier|private
parameter_list|<
name|T
parameter_list|>
name|void
name|assertNoMorePermutations
parameter_list|(
name|Iterator
argument_list|<
name|List
argument_list|<
name|T
argument_list|>
argument_list|>
name|permutations
parameter_list|)
block|{
name|assertFalse
argument_list|(
literal|"Expected no more permutations, but there was one."
argument_list|,
name|permutations
operator|.
name|hasNext
argument_list|()
argument_list|)
expr_stmt|;
try|try
block|{
name|permutations
operator|.
name|next
argument_list|()
expr_stmt|;
name|fail
argument_list|(
literal|"Expected NoSuchElementException."
argument_list|)
expr_stmt|;
block|}
catch|catch
parameter_list|(
name|NoSuchElementException
name|expected
parameter_list|)
block|{}
block|}
DECL|method|assertPermutationsCount (int expected, Collection<List<T>> permutationSet)
specifier|private
parameter_list|<
name|T
parameter_list|>
name|void
name|assertPermutationsCount
parameter_list|(
name|int
name|expected
parameter_list|,
name|Collection
argument_list|<
name|List
argument_list|<
name|T
argument_list|>
argument_list|>
name|permutationSet
parameter_list|)
block|{
name|assertEquals
argument_list|(
name|expected
argument_list|,
name|permutationSet
operator|.
name|size
argument_list|()
argument_list|)
expr_stmt|;
name|Iterator
argument_list|<
name|List
argument_list|<
name|T
argument_list|>
argument_list|>
name|permutations
init|=
name|permutationSet
operator|.
name|iterator
argument_list|()
decl_stmt|;
for|for
control|(
name|int
name|i
init|=
literal|0
init|;
name|i
operator|<
name|expected
condition|;
name|i
operator|++
control|)
block|{
name|assertTrue
argument_list|(
name|permutations
operator|.
name|hasNext
argument_list|()
argument_list|)
expr_stmt|;
name|permutations
operator|.
name|next
argument_list|()
expr_stmt|;
block|}
name|assertNoMorePermutations
argument_list|(
name|permutations
argument_list|)
expr_stmt|;
block|}
DECL|method|testToStringImplWithNullEntries ()
specifier|public
name|void
name|testToStringImplWithNullEntries
parameter_list|()
throws|throws
name|Exception
block|{
name|List
argument_list|<
name|String
argument_list|>
name|list
init|=
name|Lists
operator|.
name|newArrayList
argument_list|()
decl_stmt|;
name|list
operator|.
name|add
argument_list|(
literal|"foo"
argument_list|)
expr_stmt|;
name|list
operator|.
name|add
argument_list|(
literal|null
argument_list|)
expr_stmt|;
name|assertEquals
argument_list|(
name|list
operator|.
name|toString
argument_list|()
argument_list|,
name|Collections2
operator|.
name|toStringImpl
argument_list|(
name|list
argument_list|)
argument_list|)
expr_stmt|;
block|}
block|}
end_class

end_unit

