begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Copyright (C) 2008 The Guava Authors  *  * Licensed under the Apache License, Version 2.0 (the "License");  * you may not use this file except in compliance with the License.  * You may obtain a copy of the License at  *  * http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
DECL|package|com.google.common.net
package|package
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|net
package|;
end_package

begin_class
DECL|class|MediaTypeTest_gwt
specifier|public
class|class
name|MediaTypeTest_gwt
extends|extends
name|com
operator|.
name|google
operator|.
name|gwt
operator|.
name|junit
operator|.
name|client
operator|.
name|GWTTestCase
block|{
DECL|method|getModuleName ()
annotation|@
name|Override
specifier|public
name|String
name|getModuleName
parameter_list|()
block|{
return|return
literal|"com.google.common.net.testModule"
return|;
block|}
DECL|method|testCreateApplicationType ()
specifier|public
name|void
name|testCreateApplicationType
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|net
operator|.
name|MediaTypeTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|net
operator|.
name|MediaTypeTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testCreateApplicationType
argument_list|()
expr_stmt|;
block|}
DECL|method|testCreateAudioType ()
specifier|public
name|void
name|testCreateAudioType
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|net
operator|.
name|MediaTypeTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|net
operator|.
name|MediaTypeTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testCreateAudioType
argument_list|()
expr_stmt|;
block|}
DECL|method|testCreateImageType ()
specifier|public
name|void
name|testCreateImageType
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|net
operator|.
name|MediaTypeTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|net
operator|.
name|MediaTypeTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testCreateImageType
argument_list|()
expr_stmt|;
block|}
DECL|method|testCreateTextType ()
specifier|public
name|void
name|testCreateTextType
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|net
operator|.
name|MediaTypeTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|net
operator|.
name|MediaTypeTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testCreateTextType
argument_list|()
expr_stmt|;
block|}
DECL|method|testCreateVideoType ()
specifier|public
name|void
name|testCreateVideoType
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|net
operator|.
name|MediaTypeTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|net
operator|.
name|MediaTypeTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testCreateVideoType
argument_list|()
expr_stmt|;
block|}
DECL|method|testCreate_invalidSubtype ()
specifier|public
name|void
name|testCreate_invalidSubtype
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|net
operator|.
name|MediaTypeTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|net
operator|.
name|MediaTypeTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testCreate_invalidSubtype
argument_list|()
expr_stmt|;
block|}
DECL|method|testCreate_invalidType ()
specifier|public
name|void
name|testCreate_invalidType
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|net
operator|.
name|MediaTypeTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|net
operator|.
name|MediaTypeTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testCreate_invalidType
argument_list|()
expr_stmt|;
block|}
DECL|method|testCreate_wildcardTypeDeclaredSubtype ()
specifier|public
name|void
name|testCreate_wildcardTypeDeclaredSubtype
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|net
operator|.
name|MediaTypeTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|net
operator|.
name|MediaTypeTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testCreate_wildcardTypeDeclaredSubtype
argument_list|()
expr_stmt|;
block|}
DECL|method|testEquals ()
specifier|public
name|void
name|testEquals
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|net
operator|.
name|MediaTypeTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|net
operator|.
name|MediaTypeTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testEquals
argument_list|()
expr_stmt|;
block|}
DECL|method|testGetCharset ()
specifier|public
name|void
name|testGetCharset
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|net
operator|.
name|MediaTypeTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|net
operator|.
name|MediaTypeTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testGetCharset
argument_list|()
expr_stmt|;
block|}
DECL|method|testGetCharset_illegalCharset ()
specifier|public
name|void
name|testGetCharset_illegalCharset
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|net
operator|.
name|MediaTypeTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|net
operator|.
name|MediaTypeTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testGetCharset_illegalCharset
argument_list|()
expr_stmt|;
block|}
DECL|method|testGetCharset_tooMany ()
specifier|public
name|void
name|testGetCharset_tooMany
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|net
operator|.
name|MediaTypeTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|net
operator|.
name|MediaTypeTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testGetCharset_tooMany
argument_list|()
expr_stmt|;
block|}
DECL|method|testGetCharset_unsupportedCharset ()
specifier|public
name|void
name|testGetCharset_unsupportedCharset
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|net
operator|.
name|MediaTypeTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|net
operator|.
name|MediaTypeTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testGetCharset_unsupportedCharset
argument_list|()
expr_stmt|;
block|}
DECL|method|testGetParameters ()
specifier|public
name|void
name|testGetParameters
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|net
operator|.
name|MediaTypeTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|net
operator|.
name|MediaTypeTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testGetParameters
argument_list|()
expr_stmt|;
block|}
DECL|method|testGetSubtype ()
specifier|public
name|void
name|testGetSubtype
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|net
operator|.
name|MediaTypeTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|net
operator|.
name|MediaTypeTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testGetSubtype
argument_list|()
expr_stmt|;
block|}
DECL|method|testGetType ()
specifier|public
name|void
name|testGetType
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|net
operator|.
name|MediaTypeTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|net
operator|.
name|MediaTypeTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testGetType
argument_list|()
expr_stmt|;
block|}
DECL|method|testHasWildcard ()
specifier|public
name|void
name|testHasWildcard
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|net
operator|.
name|MediaTypeTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|net
operator|.
name|MediaTypeTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testHasWildcard
argument_list|()
expr_stmt|;
block|}
DECL|method|testIs ()
specifier|public
name|void
name|testIs
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|net
operator|.
name|MediaTypeTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|net
operator|.
name|MediaTypeTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testIs
argument_list|()
expr_stmt|;
block|}
DECL|method|testParse_badInput ()
specifier|public
name|void
name|testParse_badInput
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|net
operator|.
name|MediaTypeTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|net
operator|.
name|MediaTypeTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testParse_badInput
argument_list|()
expr_stmt|;
block|}
DECL|method|testParse_empty ()
specifier|public
name|void
name|testParse_empty
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|net
operator|.
name|MediaTypeTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|net
operator|.
name|MediaTypeTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testParse_empty
argument_list|()
expr_stmt|;
block|}
DECL|method|testToString ()
specifier|public
name|void
name|testToString
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|net
operator|.
name|MediaTypeTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|net
operator|.
name|MediaTypeTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testToString
argument_list|()
expr_stmt|;
block|}
DECL|method|testWithCharset ()
specifier|public
name|void
name|testWithCharset
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|net
operator|.
name|MediaTypeTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|net
operator|.
name|MediaTypeTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testWithCharset
argument_list|()
expr_stmt|;
block|}
DECL|method|testWithParameter ()
specifier|public
name|void
name|testWithParameter
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|net
operator|.
name|MediaTypeTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|net
operator|.
name|MediaTypeTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testWithParameter
argument_list|()
expr_stmt|;
block|}
DECL|method|testWithParameter_invalidAttribute ()
specifier|public
name|void
name|testWithParameter_invalidAttribute
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|net
operator|.
name|MediaTypeTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|net
operator|.
name|MediaTypeTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testWithParameter_invalidAttribute
argument_list|()
expr_stmt|;
block|}
DECL|method|testWithParameters ()
specifier|public
name|void
name|testWithParameters
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|net
operator|.
name|MediaTypeTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|net
operator|.
name|MediaTypeTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testWithParameters
argument_list|()
expr_stmt|;
block|}
DECL|method|testWithParametersIterable ()
specifier|public
name|void
name|testWithParametersIterable
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|net
operator|.
name|MediaTypeTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|net
operator|.
name|MediaTypeTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testWithParametersIterable
argument_list|()
expr_stmt|;
block|}
DECL|method|testWithParametersIterable_invalidAttribute ()
specifier|public
name|void
name|testWithParametersIterable_invalidAttribute
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|net
operator|.
name|MediaTypeTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|net
operator|.
name|MediaTypeTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testWithParametersIterable_invalidAttribute
argument_list|()
expr_stmt|;
block|}
DECL|method|testWithParametersIterable_nullValue ()
specifier|public
name|void
name|testWithParametersIterable_nullValue
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|net
operator|.
name|MediaTypeTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|net
operator|.
name|MediaTypeTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testWithParametersIterable_nullValue
argument_list|()
expr_stmt|;
block|}
DECL|method|testWithParameters_invalidAttribute ()
specifier|public
name|void
name|testWithParameters_invalidAttribute
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|net
operator|.
name|MediaTypeTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|net
operator|.
name|MediaTypeTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testWithParameters_invalidAttribute
argument_list|()
expr_stmt|;
block|}
DECL|method|testWithoutParameters ()
specifier|public
name|void
name|testWithoutParameters
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|net
operator|.
name|MediaTypeTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|net
operator|.
name|MediaTypeTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testWithoutParameters
argument_list|()
expr_stmt|;
block|}
block|}
end_class

end_unit

