begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Copyright (C) 2008 The Guava Authors  *  * Licensed under the Apache License, Version 2.0 (the "License");  * you may not use this file except in compliance with the License.  * You may obtain a copy of the License at  *  * http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
DECL|package|com.google.common.collect
package|package
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
package|;
end_package

begin_class
DECL|class|EvictingQueueTest_gwt
specifier|public
class|class
name|EvictingQueueTest_gwt
extends|extends
name|com
operator|.
name|google
operator|.
name|gwt
operator|.
name|junit
operator|.
name|client
operator|.
name|GWTTestCase
block|{
DECL|method|getModuleName ()
annotation|@
name|Override
specifier|public
name|String
name|getModuleName
parameter_list|()
block|{
return|return
literal|"com.google.common.collect.testModule"
return|;
block|}
DECL|method|testAddAll ()
specifier|public
name|void
name|testAddAll
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|EvictingQueueTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|EvictingQueueTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testAddAll
argument_list|()
expr_stmt|;
block|}
DECL|method|testCreateWithNegativeSize ()
specifier|public
name|void
name|testCreateWithNegativeSize
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|EvictingQueueTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|EvictingQueueTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testCreateWithNegativeSize
argument_list|()
expr_stmt|;
block|}
DECL|method|testCreateWithZeroSize ()
specifier|public
name|void
name|testCreateWithZeroSize
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|EvictingQueueTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|EvictingQueueTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testCreateWithZeroSize
argument_list|()
expr_stmt|;
block|}
DECL|method|testEvictingAfterOne ()
specifier|public
name|void
name|testEvictingAfterOne
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|EvictingQueueTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|EvictingQueueTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testEvictingAfterOne
argument_list|()
expr_stmt|;
block|}
DECL|method|testEvictingAfterThree ()
specifier|public
name|void
name|testEvictingAfterThree
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|EvictingQueueTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|EvictingQueueTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testEvictingAfterThree
argument_list|()
expr_stmt|;
block|}
DECL|method|testRemainingCapacity_maxSize0 ()
specifier|public
name|void
name|testRemainingCapacity_maxSize0
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|EvictingQueueTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|EvictingQueueTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testRemainingCapacity_maxSize0
argument_list|()
expr_stmt|;
block|}
DECL|method|testRemainingCapacity_maxSize1 ()
specifier|public
name|void
name|testRemainingCapacity_maxSize1
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|EvictingQueueTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|EvictingQueueTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testRemainingCapacity_maxSize1
argument_list|()
expr_stmt|;
block|}
DECL|method|testRemainingCapacity_maxSize3 ()
specifier|public
name|void
name|testRemainingCapacity_maxSize3
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|EvictingQueueTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|EvictingQueueTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testRemainingCapacity_maxSize3
argument_list|()
expr_stmt|;
block|}
DECL|method|testSerialization ()
specifier|public
name|void
name|testSerialization
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|EvictingQueueTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|EvictingQueueTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testSerialization
argument_list|()
expr_stmt|;
block|}
block|}
end_class

end_unit

