begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Copyright (C) 2008 The Guava Authors  *  * Licensed under the Apache License, Version 2.0 (the "License");  * you may not use this file except in compliance with the License.  * You may obtain a copy of the License at  *  * http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
DECL|package|com.google.common.collect
package|package
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
package|;
end_package

begin_class
DECL|class|MapsTest_gwt
specifier|public
class|class
name|MapsTest_gwt
extends|extends
name|com
operator|.
name|google
operator|.
name|gwt
operator|.
name|junit
operator|.
name|client
operator|.
name|GWTTestCase
block|{
DECL|method|getModuleName ()
annotation|@
name|Override
specifier|public
name|String
name|getModuleName
parameter_list|()
block|{
return|return
literal|"com.google.common.collect.testModule"
return|;
block|}
DECL|method|testAsConverter_inverse ()
specifier|public
name|void
name|testAsConverter_inverse
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testAsConverter_inverse
argument_list|()
expr_stmt|;
block|}
DECL|method|testAsConverter_isAView ()
specifier|public
name|void
name|testAsConverter_isAView
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testAsConverter_isAView
argument_list|()
expr_stmt|;
block|}
DECL|method|testAsConverter_noMapping ()
specifier|public
name|void
name|testAsConverter_noMapping
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testAsConverter_noMapping
argument_list|()
expr_stmt|;
block|}
DECL|method|testAsConverter_nominal ()
specifier|public
name|void
name|testAsConverter_nominal
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testAsConverter_nominal
argument_list|()
expr_stmt|;
block|}
DECL|method|testAsConverter_nullConversions ()
specifier|public
name|void
name|testAsConverter_nullConversions
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testAsConverter_nullConversions
argument_list|()
expr_stmt|;
block|}
DECL|method|testAsConverter_serialization ()
specifier|public
name|void
name|testAsConverter_serialization
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testAsConverter_serialization
argument_list|()
expr_stmt|;
block|}
DECL|method|testAsConverter_toString ()
specifier|public
name|void
name|testAsConverter_toString
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testAsConverter_toString
argument_list|()
expr_stmt|;
block|}
DECL|method|testAsConverter_withNullMapping ()
specifier|public
name|void
name|testAsConverter_withNullMapping
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testAsConverter_withNullMapping
argument_list|()
expr_stmt|;
block|}
DECL|method|testAsMap ()
specifier|public
name|void
name|testAsMap
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testAsMap
argument_list|()
expr_stmt|;
block|}
DECL|method|testAsMapEmpty ()
specifier|public
name|void
name|testAsMapEmpty
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testAsMapEmpty
argument_list|()
expr_stmt|;
block|}
DECL|method|testAsMapReadsThrough ()
specifier|public
name|void
name|testAsMapReadsThrough
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testAsMapReadsThrough
argument_list|()
expr_stmt|;
block|}
DECL|method|testAsMapReturnsSortedMapForSortedSetInput ()
specifier|public
name|void
name|testAsMapReturnsSortedMapForSortedSetInput
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testAsMapReturnsSortedMapForSortedSetInput
argument_list|()
expr_stmt|;
block|}
DECL|method|testAsMapSorted ()
specifier|public
name|void
name|testAsMapSorted
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testAsMapSorted
argument_list|()
expr_stmt|;
block|}
DECL|method|testAsMapSortedEmpty ()
specifier|public
name|void
name|testAsMapSortedEmpty
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testAsMapSortedEmpty
argument_list|()
expr_stmt|;
block|}
DECL|method|testAsMapSortedReadsThrough ()
specifier|public
name|void
name|testAsMapSortedReadsThrough
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testAsMapSortedReadsThrough
argument_list|()
expr_stmt|;
block|}
DECL|method|testAsMapSortedSubViewKeySetsDoNotSupportAdd ()
specifier|public
name|void
name|testAsMapSortedSubViewKeySetsDoNotSupportAdd
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testAsMapSortedSubViewKeySetsDoNotSupportAdd
argument_list|()
expr_stmt|;
block|}
DECL|method|testAsMapSortedWritesThrough ()
specifier|public
name|void
name|testAsMapSortedWritesThrough
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testAsMapSortedWritesThrough
argument_list|()
expr_stmt|;
block|}
DECL|method|testAsMapWritesThrough ()
specifier|public
name|void
name|testAsMapWritesThrough
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testAsMapWritesThrough
argument_list|()
expr_stmt|;
block|}
DECL|method|testCapacityForLargeSizes ()
specifier|public
name|void
name|testCapacityForLargeSizes
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testCapacityForLargeSizes
argument_list|()
expr_stmt|;
block|}
DECL|method|testCapacityForNegativeSizeFails ()
specifier|public
name|void
name|testCapacityForNegativeSizeFails
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testCapacityForNegativeSizeFails
argument_list|()
expr_stmt|;
block|}
DECL|method|testConcurrentMap ()
specifier|public
name|void
name|testConcurrentMap
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testConcurrentMap
argument_list|()
expr_stmt|;
block|}
DECL|method|testEnumMap ()
specifier|public
name|void
name|testEnumMap
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testEnumMap
argument_list|()
expr_stmt|;
block|}
DECL|method|testEnumMapNullClass ()
specifier|public
name|void
name|testEnumMapNullClass
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testEnumMapNullClass
argument_list|()
expr_stmt|;
block|}
DECL|method|testEnumMapWithInitialEmptyEnumMap ()
specifier|public
name|void
name|testEnumMapWithInitialEmptyEnumMap
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testEnumMapWithInitialEmptyEnumMap
argument_list|()
expr_stmt|;
block|}
DECL|method|testEnumMapWithInitialEmptyMap ()
specifier|public
name|void
name|testEnumMapWithInitialEmptyMap
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testEnumMapWithInitialEmptyMap
argument_list|()
expr_stmt|;
block|}
DECL|method|testEnumMapWithInitialEnumMap ()
specifier|public
name|void
name|testEnumMapWithInitialEnumMap
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testEnumMapWithInitialEnumMap
argument_list|()
expr_stmt|;
block|}
DECL|method|testEnumMapWithInitialMap ()
specifier|public
name|void
name|testEnumMapWithInitialMap
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testEnumMapWithInitialMap
argument_list|()
expr_stmt|;
block|}
DECL|method|testHashMap ()
specifier|public
name|void
name|testHashMap
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testHashMap
argument_list|()
expr_stmt|;
block|}
DECL|method|testHashMapGeneralizesTypes ()
specifier|public
name|void
name|testHashMapGeneralizesTypes
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testHashMapGeneralizesTypes
argument_list|()
expr_stmt|;
block|}
DECL|method|testHashMapWithInitialMap ()
specifier|public
name|void
name|testHashMapWithInitialMap
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testHashMapWithInitialMap
argument_list|()
expr_stmt|;
block|}
DECL|method|testIdentityHashMap ()
specifier|public
name|void
name|testIdentityHashMap
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testIdentityHashMap
argument_list|()
expr_stmt|;
block|}
DECL|method|testImmutableEntry ()
specifier|public
name|void
name|testImmutableEntry
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testImmutableEntry
argument_list|()
expr_stmt|;
block|}
DECL|method|testImmutableEntryNull ()
specifier|public
name|void
name|testImmutableEntryNull
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testImmutableEntryNull
argument_list|()
expr_stmt|;
block|}
DECL|method|testLinkedHashMap ()
specifier|public
name|void
name|testLinkedHashMap
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testLinkedHashMap
argument_list|()
expr_stmt|;
block|}
DECL|method|testLinkedHashMapGeneralizesTypes ()
specifier|public
name|void
name|testLinkedHashMapGeneralizesTypes
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testLinkedHashMapGeneralizesTypes
argument_list|()
expr_stmt|;
block|}
DECL|method|testLinkedHashMapWithInitialMap ()
specifier|public
name|void
name|testLinkedHashMapWithInitialMap
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testLinkedHashMapWithInitialMap
argument_list|()
expr_stmt|;
block|}
DECL|method|testMapDifferenceEmptyEmpty ()
specifier|public
name|void
name|testMapDifferenceEmptyEmpty
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testMapDifferenceEmptyEmpty
argument_list|()
expr_stmt|;
block|}
DECL|method|testMapDifferenceEmptySingleton ()
specifier|public
name|void
name|testMapDifferenceEmptySingleton
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testMapDifferenceEmptySingleton
argument_list|()
expr_stmt|;
block|}
DECL|method|testMapDifferenceEquals ()
specifier|public
name|void
name|testMapDifferenceEquals
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testMapDifferenceEquals
argument_list|()
expr_stmt|;
block|}
DECL|method|testMapDifferenceOfSortedMapIsSorted ()
specifier|public
name|void
name|testMapDifferenceOfSortedMapIsSorted
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testMapDifferenceOfSortedMapIsSorted
argument_list|()
expr_stmt|;
block|}
DECL|method|testMapDifferencePredicateTypical ()
specifier|public
name|void
name|testMapDifferencePredicateTypical
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testMapDifferencePredicateTypical
argument_list|()
expr_stmt|;
block|}
DECL|method|testMapDifferenceSingletonEmpty ()
specifier|public
name|void
name|testMapDifferenceSingletonEmpty
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testMapDifferenceSingletonEmpty
argument_list|()
expr_stmt|;
block|}
DECL|method|testMapDifferenceTypical ()
specifier|public
name|void
name|testMapDifferenceTypical
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testMapDifferenceTypical
argument_list|()
expr_stmt|;
block|}
DECL|method|testSortedMapDifferenceEmptyEmpty ()
specifier|public
name|void
name|testSortedMapDifferenceEmptyEmpty
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testSortedMapDifferenceEmptyEmpty
argument_list|()
expr_stmt|;
block|}
DECL|method|testSortedMapDifferenceEmptySingleton ()
specifier|public
name|void
name|testSortedMapDifferenceEmptySingleton
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testSortedMapDifferenceEmptySingleton
argument_list|()
expr_stmt|;
block|}
DECL|method|testSortedMapDifferenceEquals ()
specifier|public
name|void
name|testSortedMapDifferenceEquals
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testSortedMapDifferenceEquals
argument_list|()
expr_stmt|;
block|}
DECL|method|testSortedMapDifferenceImmutable ()
specifier|public
name|void
name|testSortedMapDifferenceImmutable
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testSortedMapDifferenceImmutable
argument_list|()
expr_stmt|;
block|}
DECL|method|testSortedMapDifferenceSingletonEmpty ()
specifier|public
name|void
name|testSortedMapDifferenceSingletonEmpty
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testSortedMapDifferenceSingletonEmpty
argument_list|()
expr_stmt|;
block|}
DECL|method|testSortedMapDifferenceTypical ()
specifier|public
name|void
name|testSortedMapDifferenceTypical
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testSortedMapDifferenceTypical
argument_list|()
expr_stmt|;
block|}
DECL|method|testSortedMapTransformEntries ()
specifier|public
name|void
name|testSortedMapTransformEntries
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testSortedMapTransformEntries
argument_list|()
expr_stmt|;
block|}
DECL|method|testSortedMapTransformValues ()
specifier|public
name|void
name|testSortedMapTransformValues
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testSortedMapTransformValues
argument_list|()
expr_stmt|;
block|}
DECL|method|testSynchronizedBiMap ()
specifier|public
name|void
name|testSynchronizedBiMap
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testSynchronizedBiMap
argument_list|()
expr_stmt|;
block|}
DECL|method|testToMap ()
specifier|public
name|void
name|testToMap
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testToMap
argument_list|()
expr_stmt|;
block|}
DECL|method|testToMapIterator ()
specifier|public
name|void
name|testToMapIterator
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testToMapIterator
argument_list|()
expr_stmt|;
block|}
DECL|method|testToMapWithDuplicateKeys ()
specifier|public
name|void
name|testToMapWithDuplicateKeys
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testToMapWithDuplicateKeys
argument_list|()
expr_stmt|;
block|}
DECL|method|testToMapWithNullKeys ()
specifier|public
name|void
name|testToMapWithNullKeys
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testToMapWithNullKeys
argument_list|()
expr_stmt|;
block|}
DECL|method|testToMapWithNullValues ()
specifier|public
name|void
name|testToMapWithNullValues
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testToMapWithNullValues
argument_list|()
expr_stmt|;
block|}
DECL|method|testToStringImplWithNullKeys ()
specifier|public
name|void
name|testToStringImplWithNullKeys
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testToStringImplWithNullKeys
argument_list|()
expr_stmt|;
block|}
DECL|method|testToStringImplWithNullValues ()
specifier|public
name|void
name|testToStringImplWithNullValues
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testToStringImplWithNullValues
argument_list|()
expr_stmt|;
block|}
DECL|method|testTransformEntries ()
specifier|public
name|void
name|testTransformEntries
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testTransformEntries
argument_list|()
expr_stmt|;
block|}
DECL|method|testTransformEntriesExample ()
specifier|public
name|void
name|testTransformEntriesExample
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testTransformEntriesExample
argument_list|()
expr_stmt|;
block|}
DECL|method|testTransformEntriesGenerics ()
specifier|public
name|void
name|testTransformEntriesGenerics
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testTransformEntriesGenerics
argument_list|()
expr_stmt|;
block|}
DECL|method|testTransformEntriesSecretlySorted ()
specifier|public
name|void
name|testTransformEntriesSecretlySorted
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testTransformEntriesSecretlySorted
argument_list|()
expr_stmt|;
block|}
DECL|method|testTransformValues ()
specifier|public
name|void
name|testTransformValues
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testTransformValues
argument_list|()
expr_stmt|;
block|}
DECL|method|testTransformValuesSecretlySorted ()
specifier|public
name|void
name|testTransformValuesSecretlySorted
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testTransformValuesSecretlySorted
argument_list|()
expr_stmt|;
block|}
DECL|method|testTreeMap ()
specifier|public
name|void
name|testTreeMap
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testTreeMap
argument_list|()
expr_stmt|;
block|}
DECL|method|testTreeMapDerived ()
specifier|public
name|void
name|testTreeMapDerived
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testTreeMapDerived
argument_list|()
expr_stmt|;
block|}
DECL|method|testTreeMapNonGeneric ()
specifier|public
name|void
name|testTreeMapNonGeneric
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testTreeMapNonGeneric
argument_list|()
expr_stmt|;
block|}
DECL|method|testTreeMapWithComparator ()
specifier|public
name|void
name|testTreeMapWithComparator
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testTreeMapWithComparator
argument_list|()
expr_stmt|;
block|}
DECL|method|testTreeMapWithInitialMap ()
specifier|public
name|void
name|testTreeMapWithInitialMap
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testTreeMapWithInitialMap
argument_list|()
expr_stmt|;
block|}
DECL|method|testUniqueIndexCollection ()
specifier|public
name|void
name|testUniqueIndexCollection
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testUniqueIndexCollection
argument_list|()
expr_stmt|;
block|}
DECL|method|testUniqueIndexDuplicates ()
specifier|public
name|void
name|testUniqueIndexDuplicates
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testUniqueIndexDuplicates
argument_list|()
expr_stmt|;
block|}
DECL|method|testUniqueIndexIterable ()
specifier|public
name|void
name|testUniqueIndexIterable
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testUniqueIndexIterable
argument_list|()
expr_stmt|;
block|}
DECL|method|testUniqueIndexIterator ()
specifier|public
name|void
name|testUniqueIndexIterator
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testUniqueIndexIterator
argument_list|()
expr_stmt|;
block|}
DECL|method|testUniqueIndexNullKey ()
specifier|public
name|void
name|testUniqueIndexNullKey
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testUniqueIndexNullKey
argument_list|()
expr_stmt|;
block|}
DECL|method|testUniqueIndexNullValue ()
specifier|public
name|void
name|testUniqueIndexNullValue
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testUniqueIndexNullValue
argument_list|()
expr_stmt|;
block|}
DECL|method|testUnmodifiableBiMap ()
specifier|public
name|void
name|testUnmodifiableBiMap
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testUnmodifiableBiMap
argument_list|()
expr_stmt|;
block|}
DECL|method|testFilterEntriesIdentifiesBiMap__FilteredBiMapTest ()
specifier|public
name|void
name|testFilterEntriesIdentifiesBiMap__FilteredBiMapTest
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
operator|.
name|FilteredBiMapTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
operator|.
name|FilteredBiMapTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testFilterEntriesIdentifiesBiMap
argument_list|()
expr_stmt|;
block|}
DECL|method|testFilterKeysIdentifiesBiMap__FilteredBiMapTest ()
specifier|public
name|void
name|testFilterKeysIdentifiesBiMap__FilteredBiMapTest
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
operator|.
name|FilteredBiMapTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
operator|.
name|FilteredBiMapTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testFilterKeysIdentifiesBiMap
argument_list|()
expr_stmt|;
block|}
DECL|method|testFilterValuesIdentifiesBiMap__FilteredBiMapTest ()
specifier|public
name|void
name|testFilterValuesIdentifiesBiMap__FilteredBiMapTest
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
operator|.
name|FilteredBiMapTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
operator|.
name|FilteredBiMapTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testFilterValuesIdentifiesBiMap
argument_list|()
expr_stmt|;
block|}
DECL|method|testFilteredEntriesIllegalPut__FilteredBiMapTest ()
specifier|public
name|void
name|testFilteredEntriesIllegalPut__FilteredBiMapTest
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
operator|.
name|FilteredBiMapTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
operator|.
name|FilteredBiMapTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testFilteredEntriesIllegalPut
argument_list|()
expr_stmt|;
block|}
DECL|method|testFilteredEntriesIllegalPutAll__FilteredBiMapTest ()
specifier|public
name|void
name|testFilteredEntriesIllegalPutAll__FilteredBiMapTest
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
operator|.
name|FilteredBiMapTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
operator|.
name|FilteredBiMapTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testFilteredEntriesIllegalPutAll
argument_list|()
expr_stmt|;
block|}
DECL|method|testFilteredEntriesObjectPredicate__FilteredBiMapTest ()
specifier|public
name|void
name|testFilteredEntriesObjectPredicate__FilteredBiMapTest
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
operator|.
name|FilteredBiMapTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
operator|.
name|FilteredBiMapTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testFilteredEntriesObjectPredicate
argument_list|()
expr_stmt|;
block|}
DECL|method|testFilteredEntriesWildCardEntryPredicate__FilteredBiMapTest ()
specifier|public
name|void
name|testFilteredEntriesWildCardEntryPredicate__FilteredBiMapTest
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
operator|.
name|FilteredBiMapTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
operator|.
name|FilteredBiMapTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testFilteredEntriesWildCardEntryPredicate
argument_list|()
expr_stmt|;
block|}
DECL|method|testFilteredKeysFilteredReflectsBackingChanges__FilteredBiMapTest ()
specifier|public
name|void
name|testFilteredKeysFilteredReflectsBackingChanges__FilteredBiMapTest
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
operator|.
name|FilteredBiMapTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
operator|.
name|FilteredBiMapTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testFilteredKeysFilteredReflectsBackingChanges
argument_list|()
expr_stmt|;
block|}
DECL|method|testFilteredKeysIllegalPut__FilteredBiMapTest ()
specifier|public
name|void
name|testFilteredKeysIllegalPut__FilteredBiMapTest
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
operator|.
name|FilteredBiMapTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
operator|.
name|FilteredBiMapTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testFilteredKeysIllegalPut
argument_list|()
expr_stmt|;
block|}
DECL|method|testFilteredKeysIllegalPutAll__FilteredBiMapTest ()
specifier|public
name|void
name|testFilteredKeysIllegalPutAll__FilteredBiMapTest
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
operator|.
name|FilteredBiMapTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
operator|.
name|FilteredBiMapTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testFilteredKeysIllegalPutAll
argument_list|()
expr_stmt|;
block|}
DECL|method|testFilteredValuesClear__FilteredBiMapTest ()
specifier|public
name|void
name|testFilteredValuesClear__FilteredBiMapTest
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
operator|.
name|FilteredBiMapTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
operator|.
name|FilteredBiMapTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testFilteredValuesClear
argument_list|()
expr_stmt|;
block|}
DECL|method|testFilteredValuesIllegalPut__FilteredBiMapTest ()
specifier|public
name|void
name|testFilteredValuesIllegalPut__FilteredBiMapTest
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
operator|.
name|FilteredBiMapTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
operator|.
name|FilteredBiMapTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testFilteredValuesIllegalPut
argument_list|()
expr_stmt|;
block|}
DECL|method|testFilteredValuesIllegalPutAll__FilteredBiMapTest ()
specifier|public
name|void
name|testFilteredValuesIllegalPutAll__FilteredBiMapTest
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
operator|.
name|FilteredBiMapTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
operator|.
name|FilteredBiMapTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testFilteredValuesIllegalPutAll
argument_list|()
expr_stmt|;
block|}
DECL|method|testFilteredValuesIllegalSetValue__FilteredBiMapTest ()
specifier|public
name|void
name|testFilteredValuesIllegalSetValue__FilteredBiMapTest
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
operator|.
name|FilteredBiMapTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
operator|.
name|FilteredBiMapTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testFilteredValuesIllegalSetValue
argument_list|()
expr_stmt|;
block|}
DECL|method|testFilterEntriesIdentifiesSortedMap__FilteredSortedMapTest ()
specifier|public
name|void
name|testFilterEntriesIdentifiesSortedMap__FilteredSortedMapTest
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
operator|.
name|FilteredSortedMapTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
operator|.
name|FilteredSortedMapTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testFilterEntriesIdentifiesSortedMap
argument_list|()
expr_stmt|;
block|}
DECL|method|testFilterKeysIdentifiesSortedMap__FilteredSortedMapTest ()
specifier|public
name|void
name|testFilterKeysIdentifiesSortedMap__FilteredSortedMapTest
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
operator|.
name|FilteredSortedMapTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
operator|.
name|FilteredSortedMapTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testFilterKeysIdentifiesSortedMap
argument_list|()
expr_stmt|;
block|}
DECL|method|testFilterValuesIdentifiesSortedMap__FilteredSortedMapTest ()
specifier|public
name|void
name|testFilterValuesIdentifiesSortedMap__FilteredSortedMapTest
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
operator|.
name|FilteredSortedMapTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
operator|.
name|FilteredSortedMapTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testFilterValuesIdentifiesSortedMap
argument_list|()
expr_stmt|;
block|}
DECL|method|testFilteredEntriesIllegalPut__FilteredSortedMapTest ()
specifier|public
name|void
name|testFilteredEntriesIllegalPut__FilteredSortedMapTest
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
operator|.
name|FilteredSortedMapTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
operator|.
name|FilteredSortedMapTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testFilteredEntriesIllegalPut
argument_list|()
expr_stmt|;
block|}
DECL|method|testFilteredEntriesIllegalPutAll__FilteredSortedMapTest ()
specifier|public
name|void
name|testFilteredEntriesIllegalPutAll__FilteredSortedMapTest
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
operator|.
name|FilteredSortedMapTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
operator|.
name|FilteredSortedMapTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testFilteredEntriesIllegalPutAll
argument_list|()
expr_stmt|;
block|}
DECL|method|testFilteredEntriesObjectPredicate__FilteredSortedMapTest ()
specifier|public
name|void
name|testFilteredEntriesObjectPredicate__FilteredSortedMapTest
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
operator|.
name|FilteredSortedMapTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
operator|.
name|FilteredSortedMapTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testFilteredEntriesObjectPredicate
argument_list|()
expr_stmt|;
block|}
DECL|method|testFilteredEntriesWildCardEntryPredicate__FilteredSortedMapTest ()
specifier|public
name|void
name|testFilteredEntriesWildCardEntryPredicate__FilteredSortedMapTest
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
operator|.
name|FilteredSortedMapTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
operator|.
name|FilteredSortedMapTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testFilteredEntriesWildCardEntryPredicate
argument_list|()
expr_stmt|;
block|}
DECL|method|testFilteredKeysFilteredReflectsBackingChanges__FilteredSortedMapTest ()
specifier|public
name|void
name|testFilteredKeysFilteredReflectsBackingChanges__FilteredSortedMapTest
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
operator|.
name|FilteredSortedMapTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
operator|.
name|FilteredSortedMapTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testFilteredKeysFilteredReflectsBackingChanges
argument_list|()
expr_stmt|;
block|}
DECL|method|testFilteredKeysIllegalPut__FilteredSortedMapTest ()
specifier|public
name|void
name|testFilteredKeysIllegalPut__FilteredSortedMapTest
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
operator|.
name|FilteredSortedMapTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
operator|.
name|FilteredSortedMapTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testFilteredKeysIllegalPut
argument_list|()
expr_stmt|;
block|}
DECL|method|testFilteredKeysIllegalPutAll__FilteredSortedMapTest ()
specifier|public
name|void
name|testFilteredKeysIllegalPutAll__FilteredSortedMapTest
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
operator|.
name|FilteredSortedMapTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
operator|.
name|FilteredSortedMapTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testFilteredKeysIllegalPutAll
argument_list|()
expr_stmt|;
block|}
DECL|method|testFilteredValuesClear__FilteredSortedMapTest ()
specifier|public
name|void
name|testFilteredValuesClear__FilteredSortedMapTest
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
operator|.
name|FilteredSortedMapTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
operator|.
name|FilteredSortedMapTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testFilteredValuesClear
argument_list|()
expr_stmt|;
block|}
DECL|method|testFilteredValuesIllegalPut__FilteredSortedMapTest ()
specifier|public
name|void
name|testFilteredValuesIllegalPut__FilteredSortedMapTest
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
operator|.
name|FilteredSortedMapTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
operator|.
name|FilteredSortedMapTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testFilteredValuesIllegalPut
argument_list|()
expr_stmt|;
block|}
DECL|method|testFilteredValuesIllegalPutAll__FilteredSortedMapTest ()
specifier|public
name|void
name|testFilteredValuesIllegalPutAll__FilteredSortedMapTest
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
operator|.
name|FilteredSortedMapTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
operator|.
name|FilteredSortedMapTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testFilteredValuesIllegalPutAll
argument_list|()
expr_stmt|;
block|}
DECL|method|testFilteredValuesIllegalSetValue__FilteredSortedMapTest ()
specifier|public
name|void
name|testFilteredValuesIllegalSetValue__FilteredSortedMapTest
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
operator|.
name|FilteredSortedMapTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
operator|.
name|FilteredSortedMapTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testFilteredValuesIllegalSetValue
argument_list|()
expr_stmt|;
block|}
DECL|method|testFirstAndLastKeyFilteredMap__FilteredSortedMapTest ()
specifier|public
name|void
name|testFirstAndLastKeyFilteredMap__FilteredSortedMapTest
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
operator|.
name|FilteredSortedMapTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
operator|.
name|FilteredSortedMapTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testFirstAndLastKeyFilteredMap
argument_list|()
expr_stmt|;
block|}
DECL|method|testHeadSubTailMap_FilteredMap__FilteredSortedMapTest ()
specifier|public
name|void
name|testHeadSubTailMap_FilteredMap__FilteredSortedMapTest
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
operator|.
name|FilteredSortedMapTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
operator|.
name|FilteredSortedMapTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testHeadSubTailMap_FilteredMap
argument_list|()
expr_stmt|;
block|}
DECL|method|testFilteredEntriesIllegalPut__FilteredMapTest ()
specifier|public
name|void
name|testFilteredEntriesIllegalPut__FilteredMapTest
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
operator|.
name|FilteredMapTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
operator|.
name|FilteredMapTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testFilteredEntriesIllegalPut
argument_list|()
expr_stmt|;
block|}
DECL|method|testFilteredEntriesIllegalPutAll__FilteredMapTest ()
specifier|public
name|void
name|testFilteredEntriesIllegalPutAll__FilteredMapTest
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
operator|.
name|FilteredMapTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
operator|.
name|FilteredMapTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testFilteredEntriesIllegalPutAll
argument_list|()
expr_stmt|;
block|}
DECL|method|testFilteredEntriesObjectPredicate__FilteredMapTest ()
specifier|public
name|void
name|testFilteredEntriesObjectPredicate__FilteredMapTest
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
operator|.
name|FilteredMapTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
operator|.
name|FilteredMapTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testFilteredEntriesObjectPredicate
argument_list|()
expr_stmt|;
block|}
DECL|method|testFilteredEntriesWildCardEntryPredicate__FilteredMapTest ()
specifier|public
name|void
name|testFilteredEntriesWildCardEntryPredicate__FilteredMapTest
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
operator|.
name|FilteredMapTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
operator|.
name|FilteredMapTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testFilteredEntriesWildCardEntryPredicate
argument_list|()
expr_stmt|;
block|}
DECL|method|testFilteredKeysFilteredReflectsBackingChanges__FilteredMapTest ()
specifier|public
name|void
name|testFilteredKeysFilteredReflectsBackingChanges__FilteredMapTest
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
operator|.
name|FilteredMapTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
operator|.
name|FilteredMapTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testFilteredKeysFilteredReflectsBackingChanges
argument_list|()
expr_stmt|;
block|}
DECL|method|testFilteredKeysIllegalPut__FilteredMapTest ()
specifier|public
name|void
name|testFilteredKeysIllegalPut__FilteredMapTest
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
operator|.
name|FilteredMapTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
operator|.
name|FilteredMapTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testFilteredKeysIllegalPut
argument_list|()
expr_stmt|;
block|}
DECL|method|testFilteredKeysIllegalPutAll__FilteredMapTest ()
specifier|public
name|void
name|testFilteredKeysIllegalPutAll__FilteredMapTest
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
operator|.
name|FilteredMapTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
operator|.
name|FilteredMapTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testFilteredKeysIllegalPutAll
argument_list|()
expr_stmt|;
block|}
DECL|method|testFilteredValuesClear__FilteredMapTest ()
specifier|public
name|void
name|testFilteredValuesClear__FilteredMapTest
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
operator|.
name|FilteredMapTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
operator|.
name|FilteredMapTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testFilteredValuesClear
argument_list|()
expr_stmt|;
block|}
DECL|method|testFilteredValuesIllegalPut__FilteredMapTest ()
specifier|public
name|void
name|testFilteredValuesIllegalPut__FilteredMapTest
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
operator|.
name|FilteredMapTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
operator|.
name|FilteredMapTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testFilteredValuesIllegalPut
argument_list|()
expr_stmt|;
block|}
DECL|method|testFilteredValuesIllegalPutAll__FilteredMapTest ()
specifier|public
name|void
name|testFilteredValuesIllegalPutAll__FilteredMapTest
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
operator|.
name|FilteredMapTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
operator|.
name|FilteredMapTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testFilteredValuesIllegalPutAll
argument_list|()
expr_stmt|;
block|}
DECL|method|testFilteredValuesIllegalSetValue__FilteredMapTest ()
specifier|public
name|void
name|testFilteredValuesIllegalSetValue__FilteredMapTest
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
operator|.
name|FilteredMapTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|MapsTest
operator|.
name|FilteredMapTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testFilteredValuesIllegalSetValue
argument_list|()
expr_stmt|;
block|}
block|}
end_class

end_unit

