begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Copyright (C) 2008 The Guava Authors  *  * Licensed under the Apache License, Version 2.0 (the "License");  * you may not use this file except in compliance with the License.  * You may obtain a copy of the License at  *  * http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
DECL|package|com.google.common.collect
package|package
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
package|;
end_package

begin_class
DECL|class|WellBehavedMapTest_gwt
specifier|public
class|class
name|WellBehavedMapTest_gwt
extends|extends
name|com
operator|.
name|google
operator|.
name|gwt
operator|.
name|junit
operator|.
name|client
operator|.
name|GWTTestCase
block|{
DECL|method|getModuleName ()
annotation|@
name|Override
specifier|public
name|String
name|getModuleName
parameter_list|()
block|{
return|return
literal|"com.google.common.collect.testModule"
return|;
block|}
DECL|method|testEntriesAreMutableAndConsistent ()
specifier|public
name|void
name|testEntriesAreMutableAndConsistent
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|WellBehavedMapTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|WellBehavedMapTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testEntriesAreMutableAndConsistent
argument_list|()
expr_stmt|;
block|}
DECL|method|testEntrySet_contain ()
specifier|public
name|void
name|testEntrySet_contain
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|WellBehavedMapTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|WellBehavedMapTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testEntrySet_contain
argument_list|()
expr_stmt|;
block|}
DECL|method|testEntrySet_remove ()
specifier|public
name|void
name|testEntrySet_remove
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|WellBehavedMapTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|WellBehavedMapTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testEntrySet_remove
argument_list|()
expr_stmt|;
block|}
DECL|method|testEntry_setValue ()
specifier|public
name|void
name|testEntry_setValue
parameter_list|()
throws|throws
name|Exception
block|{
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|WellBehavedMapTest
name|testCase
init|=
operator|new
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|WellBehavedMapTest
argument_list|()
decl_stmt|;
name|testCase
operator|.
name|testEntry_setValue
argument_list|()
expr_stmt|;
block|}
block|}
end_class

end_unit

